In [1]:
import pandas as pd

In [2]:
refseq_metadata = pd.read_csv("assembly_summary.txt",sep='\t',skiprows=[0],dtype='str')

In [3]:
patric_metadata = pd.read_csv("genome_metadata",sep='\t',dtype='str')

In [7]:
patric_metadata['genome_status'].value_counts()

genome_status
WGS           920251
Deprecated     66429
Complete       55066
Plasmid        15690
Name: count, dtype: int64

In [9]:
patric_metadata_filtered = patric_metadata[patric_metadata['refseq_accessions'].notna()]
patric_metadata_filtered

,genome_id,genome_name,organism_name,taxon_id,genome_status,strain,serovar,biovar,pathovar,mlst,...,motility,sporulation,temperature_range,optimal_temperature,salinity,oxygen_requirement,habitat,disease,comments,additional_metadata
1,1309411.5,"""'Deinococcus soli' Cha et al. 2014 strain N5""",NaN,1309411,Complete,N5,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Genome sequencing of a Gamma-Radiation-Resista...,sample_type:bacterial
3,551115.6,"""'Nostoc azollae' 0708""",'Nostoc azollae' 0708,551115,Complete,708,NaN,NaN,NaN,NaN,...,Yes,NaN,Mesophilic,-,NaN,Aerobic,Multiple,NaN,"Nostoc azollae 0708. Nostoc azollae 0708, also...",NaN
34,483218.5,"""[Bacteroides] pectinophilus ATCC 43243""",Bacteroides pectinophilus ATCC 43243,483218,WGS,ATCC 43243,NaN,NaN,NaN,NaN,...,No,No,Mesophilic,35-40,NaN,Anaerobic,Host-associated,NaN,Bacteroides pectinophilus ATCC 43243. Bactero...,NaN
35,1232385.4,"""[Brevibacterium] flavum ZL-1""",NaN,1232385,Complete,ZL-1,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Produces lysine, L-lysine.",NaN
36,92706.3,"""[Brevibacterium] flavum strain ATCC 15168""",NaN,92706,Complete,ATCC 15168,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,metabolic engineering for valine production,sample_type:Single cell
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1059041,1131286.3,zeta proteobacterium SCGC AB-137-J06,zeta proteobacterium SCGC AB-137-J06,1131286,WGS,SCGC AB-137-J06,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Single cell genome sequencing of biomineralizi...,NaN
1059042,1131287.3,zeta proteobacterium SCGC AB-602-C20,zeta proteobacterium SCGC AB-602-C20,1131287,WGS,SCGC AB-602-C20,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Single cell genome sequencing of biomineralizi...,NaN
1059043,1131288.3,zeta proteobacterium SCGC AB-602-E04,zeta proteobacterium SCGC AB-602-E04,1131288,WGS,SCGC AB-602-E04,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Single cell genome sequencing of biomineralizi...,NaN
1059044,1131289.3,zeta proteobacterium SCGC AB-604-B04,zeta proteobacterium SCGC AB-604-B04,1131289,WGS,SCGC AB-604-B04,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Single cell genome sequencing of biomineralizi...,NaN
1059045,1131290.3,zeta proteobacterium SCGC AB-604-O16,zeta proteobacterium SCGC AB-604-O16,1131290,WGS,SCGC AB-604-O16,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Single cell genome sequencing of biomineralizi...,NaN

In [15]:
patric_metadata_filtered = patric_metadata[patric_metadata['genome_id'].isna()]

patric_metadata_filtered

Empty DataFrame
Columns: [genome_id, genome_name, organism_name, taxon_id, genome_status, strain, serovar, biovar, pathovar, mlst, other_typing, culture_collection, type_strain, completion_date, publication, bioproject_accession, biosample_accession, assembly_accession, genbank_accessions, refseq_accessions, sequencing_centers, sequencing_status, sequencing_platform, sequencing_depth, assembly_method, chromosomes, plasmids, contigs, sequences, genome_length, gc_content, patric_cds, brc1_cds, refseq_cds, isolation_site, isolation_source, isolation_comments, collection_date, isolation_country, geographic_location, latitude, longitude, altitude, depth, other_environmental, host_name, host_gender, host_age, host_health, body_sample_site, body_sample_subsite, other_clinical, antimicrobial_resistance, antimicrobial_resistance_evidence, gram_stain, cell_shape, motility, sporulation, temperature_range, optimal_temperature, salinity, oxygen_requirement, habitat, disease, comments, additional_metadata]
Index: []

[0 rows x 66 columns]

In [16]:
refseq_metadata_filtered = refseq_metadata[refseq_metadata['#assembly_accession'].isna()]
refseq_metadata_filtered

Empty DataFrame
Columns: [#assembly_accession, bioproject, biosample, wgs_master, refseq_category, taxid, species_taxid, organism_name, infraspecific_name, isolate, version_status, assembly_level, release_type, genome_rep, seq_rel_date, asm_name, asm_submitter, gbrs_paired_asm, paired_asm_comp, ftp_path, excluded_from_refseq, relation_to_type_material, asm_not_live_date, assembly_type, group, genome_size, genome_size_ungapped, gc_percent, replicon_count, scaffold_count, contig_count, annotation_provider, annotation_name, annotation_date, total_gene_count, protein_coding_gene_count, non_coding_gene_count, pubmed_id]
Index: []

[0 rows x 38 columns]

In [9]:
patric_metadata['taxon_id'].value_counts()

taxon_id
562        58906
1773       42792
1313       29643
573        28495
1280       19675
           ...
180856         1
483218         1
1232385        1
429581         1
136143         1
Name: count, Length: 104336, dtype: int64

In [23]:
refseq_metadata['assembly_level'].value_counts()

assembly_level
Contig             220691
Scaffold           131559
Complete Genome     46756
Chromosome           5912
Name: count, dtype: int64

In [15]:
ecoli = patric_metadata[patric_metadata['taxon_id']=='562']
ecoli['strain'].value_counts().head(20)

strain
not applicable    661
Fecal samples     634
Not applicable     77
not collected      67
blood              46
E. coli            43
stool              33
131                27
10                 26
20                 19
15                 19
E2                 19
16                 18
11                 18
17                 17
9                  16
4                  16
127                16
ST73               16
7                  15
Name: count, dtype: int64

In [16]:
ecoli = refseq_metadata[refseq_metadata['taxid']=='562']
ecoli['infraspecific_name'].value_counts().head(20)

infraspecific_name
na                             1435
strain=ST73                      16
strain=E2                        12
ecotype=Quinolone resistant      12
strain=EC2                       12
strain=EC1                       11
strain=EC11                      10
strain=EC3                       10
strain=EC14                      10
strain=10                         9
strain=2                          9
strain=15                         9
strain=EC12                       9
strain=EC13                       9
strain=E4                         9
strain=EC15                       9
strain=K-12                       8
strain=ECO3347                    8
strain=12                         8
strain=EC4                        8
Name: count, dtype: int64

In [ ]:
# Step 1: Filter by taxid 562 and strain 
df_taxid_562 = refseq_metadata[refseq_metadata['taxid'] == '562']
df_taxid_562 = df_taxid_562[df_taxid_562['infraspecific_name'] == 'strain=ST73']

# Step 2: Sort by the 'annotation_date' column (ensure it's in datetime format if necessary)
df_taxid_562['annotation_date'] = pd.to_datetime(df_taxid_562['annotation_date'])
df_taxid_562_sorted = df_taxid_562.sort_values(by='annotation_date', ascending=False)

# Step 3: Clean and convert 'genome_size' to numeric (if necessary)
df_taxid_562_sorted['genome_size'] = df_taxid_562_sorted['genome_size'].replace({r'[^\d.]': ''}, regex=True)
df_taxid_562_sorted['genome_size'] = pd.to_numeric(df_taxid_562_sorted['genome_size'], errors='coerce')

# Step 4: Select the latest assembly, and if there are still multiple rows, pick the one with the longest genome size
df_taxid_562_latest = df_taxid_562_sorted.iloc[0]  # Select the latest assembly
if len(df_taxid_562_sorted) > 1:
    df_taxid_562_latest = df_taxid_562_sorted.nlargest(1, 'genome_size')

df_taxid_562_latest

,#assembly_accession,bioproject,biosample,wgs_master,refseq_category,taxid,species_taxid,organism_name,infraspecific_name,isolate,...,replicon_count,scaffold_count,contig_count,annotation_provider,annotation_name,annotation_date,total_gene_count,protein_coding_gene_count,non_coding_gene_count,pubmed_id
79721,GCF_900536975.1,PRJNA224116,SAMEA104446543,UNQS00000000.1,na,562,562,Escherichia coli,strain=ST73,2009_3,...,0,138,138,NCBI RefSeq,GCF_900536975.1-RS_2024_06_17,2024-06-17,5338,4876,97,na

In [26]:
refseq_metadata  = refseq_metadata[refseq_metadata['infraspecific_name']!='na']

In [ ]:
import pandas as pd

# Assuming 'refseq_metadata' is your DataFrame
def select_latest_assembly(group):
    # Sort by 'annotation_date' and convert to datetime if necessary
    group['annotation_date'] = pd.to_datetime(group['annotation_date'])
    group_sorted = group.sort_values(by='annotation_date', ascending=False)
    
    # Clean and convert 'genome_size' to numeric
    group_sorted['genome_size'] = group_sorted['genome_size'].replace({r'[^\d.]': ''}, regex=True)
    group_sorted['genome_size'] = pd.to_numeric(group_sorted['genome_size'], errors='coerce')
    
    # Select the latest assembly, and if there are still multiple rows, pick the one with the longest genome size
    latest_assembly = group_sorted.iloc[0]  # Select the latest assembly
    if len(group_sorted) > 1:
        latest_assembly = group_sorted.nlargest(1, 'genome_size').iloc[0]
    
    return latest_assembly

# Apply the function to each group (grouped by 'taxid' and 'infraspecific_name')
df_unique_assemblies = refseq_metadata.groupby(['taxid', 'infraspecific_name'], group_keys=False).apply(select_latest_assembly)

# The result will contain the unique assembly for each strain
df_unique_assemblies

In [31]:
df_unique_assemblies['infraspecific_name'].value_counts()

infraspecific_name
strain=BIOML-A1      71
strain=BIOML-A2      53
strain=S1            49
strain=BIOML-A3      49
strain=C1            47
                     ..
strain=CCUG 60898     1
strain=TA208          1
strain=39T            1
strain=DSM 24617      1
strain=WGS1921        1
Name: count, Length: 329564, dtype: int64

In [32]:
df_unique_assemblies.to_csv("refseq_representative_assemblies.csv")

In [43]:
patric_metadata['strain'].value_counts()

strain
B31 5A4                   966
CO275                     769
Neisseria meningitidis    542
B31 5A3                   439
5A18NP1                   284
                         ...
YR_bin-0414                 1
YR_bin-2355                 1
N43453                      1
N43451                      1
N43450                      1
Name: count, Length: 878075, dtype: int64

In [41]:
patric_metadata = patric_metadata[patric_metadata['strain']!='not applicable']
patric_metadata = patric_metadata[patric_metadata['strain']!='Not applicable']
patric_metadata = patric_metadata[patric_metadata['strain']!='Fecal samples']
patric_metadata = patric_metadata[patric_metadata['strain']!='not collected']

In [45]:
patric_metadata.columns

Index(['genome_id', 'genome_name', 'organism_name', 'taxon_id',
       'genome_status', 'strain', 'serovar', 'biovar', 'pathovar', 'mlst',
       'other_typing', 'culture_collection', 'type_strain', 'completion_date',
       'publication', 'bioproject_accession', 'biosample_accession',
       'assembly_accession', 'genbank_accessions', 'refseq_accessions',
       'sequencing_centers', 'sequencing_status', 'sequencing_platform',
       'sequencing_depth', 'assembly_method', 'chromosomes', 'plasmids',
       'contigs', 'sequences', 'genome_length', 'gc_content', 'patric_cds',
       'brc1_cds', 'refseq_cds', 'isolation_site', 'isolation_source',
       'isolation_comments', 'collection_date', 'isolation_country',
       'geographic_location', 'latitude', 'longitude', 'altitude', 'depth',
       'other_environmental', 'host_name', 'host_gender', 'host_age',
       'host_health', 'body_sample_site', 'body_sample_subsite',
       'other_clinical', 'antimicrobial_resistance',
       'antimicrobial_resistance_evidence', 'gram_stain', 'cell_shape',
       'motility', 'sporulation', 'temperature_range', 'optimal_temperature',
       'salinity', 'oxygen_requirement', 'habitat', 'disease', 'comments',
       'additional_metadata'],
      dtype='object')

In [51]:
df_unique_assemblies_patric.to_csv("patric_representative_assemblies.csv")

In [ ]:
import pandas as pd

# Assuming 'refseq_metadata' is your DataFrame
def select_latest_assembly(group):
    # Sort by 'annotation_date' and convert to datetime if necessary
    group['completion_date'] = pd.to_datetime(group['completion_date'])
    group_sorted = group.sort_values(by='completion_date', ascending=False)
    
    # Clean and convert 'genome_size' to numeric
    group_sorted['genome_length'] = group_sorted['genome_length'].replace({r'[^\d.]': ''}, regex=True)
    group_sorted['genome_length'] = pd.to_numeric(group_sorted['genome_length'], errors='coerce')
    
    # Select the latest assembly, and if there are still multiple rows, pick the one with the longest genome size
    latest_assembly = group_sorted.iloc[0]  # Select the latest assembly
    if len(group_sorted) > 1:
        latest_assembly = group_sorted.nlargest(1, 'genome_length').iloc[0]
    
    return latest_assembly

# Apply the function to each group (grouped by 'taxid' and 'infraspecific_name')
df_unique_assemblies_patric = patric_metadata.groupby(['taxon_id', 'strain'], group_keys=False).apply(select_latest_assembly)

# The result will contain the unique assembly for each strain
df_unique_assemblies_patric

In [52]:
df_unique_assemblies_patric

                    genome_id  \
taxon_id strain
100      DSM 101       100.11
         UV5            100.9
100053   56159       100053.7
         56640       100053.6
         56643       100053.5
...                       ...
999894   HyVt-483   999894.10
         S95         999894.9
999898   CEB3        999898.5
999931   39T         999931.5
         DSM 24617   999931.3

                                                          genome_name  \
taxon_id strain
100      DSM 101                Ancylobacter aquaticus strain DSM 101
         UV5                        Ancylobacter aquaticus strain UV5
100053   56159                     Leptospira alexanderi strain 56159
         56640                     Leptospira alexanderi strain 56640
         56643                     Leptospira alexanderi strain 56643
...                                                               ...
999894   HyVt-483        Thermosulfurimonas dismutans strain HyVt-483
         S95                  Thermosulfurimonas dismutans strain S95
999898   CEB3                           Peptococcaceae bacterium CEB3
999931   39T        Barrientosiimonas humi strain type strain: 39 ...
         DSM 24617            Barrientosiimonas humi strain DSM 24617

                   organism_name taxon_id genome_status     strain serovar  \
taxon_id strain
100      DSM 101             NaN      100           WGS    DSM 101     NaN
         UV5                 NaN      100           WGS        UV5     NaN
100053   56159               NaN   100053           WGS      56159     NaN
         56640               NaN   100053           WGS      56640     NaN
         56643               NaN   100053           WGS      56643     NaN
...                          ...      ...           ...        ...     ...
999894   HyVt-483            NaN   999894           WGS   HyVt-483     NaN
         S95                 NaN   999894           WGS        S95     NaN
999898   CEB3                NaN   999898           WGS       CEB3     NaN
999931   39T                 NaN   999931           WGS        39T     NaN
         DSM 24617           NaN   999931           WGS  DSM 24617     NaN

                   biovar pathovar mlst  ... motility sporulation  \
taxon_id strain                          ...
100      DSM 101      NaN      NaN  NaN  ...      NaN         NaN
         UV5          NaN      NaN  NaN  ...      NaN         NaN
100053   56159        NaN      NaN  NaN  ...      NaN         NaN
         56640        NaN      NaN  NaN  ...      NaN         NaN
         56643        NaN      NaN  NaN  ...      NaN         NaN
...                   ...      ...  ...  ...      ...         ...
999894   HyVt-483     NaN      NaN  NaN  ...      NaN         NaN
         S95          NaN      NaN  NaN  ...      NaN         NaN
999898   CEB3         NaN      NaN  NaN  ...      NaN         NaN
999931   39T          NaN      NaN  NaN  ...      NaN         NaN
         DSM 24617    NaN      NaN  NaN  ...      NaN         NaN

                   temperature_range optimal_temperature salinity  \
taxon_id strain
100      DSM 101                 NaN                 NaN      NaN
         UV5                     NaN                 NaN      NaN
100053   56159                   NaN                 NaN      NaN
         56640                   NaN                 NaN      NaN
         56643                   NaN                 NaN      NaN
...                              ...                 ...      ...
999894   HyVt-483                NaN                 NaN      NaN
         S95                     NaN                 NaN      NaN
999898   CEB3                    NaN                   C      NaN
999931   39T                     NaN                 NaN      NaN
         DSM 24617               NaN                 NaN      NaN

                   oxygen_requirement habitat disease  \
taxon_id strain
100      DSM 101                  NaN     NaN     NaN
         UV5                      NaN     NaN     NaN
100053   56159                    NaN     NaN     NaN
         56640                    NaN     NaN     NaN
         56643                    NaN     NaN     NaN
...                               ...     ...     ...
999894   HyVt-483                 NaN     NaN     NaN
         S95                      NaN     NaN     NaN
999898   CEB3                     NaN     NaN     NaN
999931   39T                      NaN     NaN     NaN
         DSM 24617                NaN     NaN     NaN

                                                             comments  \
taxon_id strain
100      DSM 101    Genome sequencing as part of The One Thousand ...
         UV5        Ancylobacter aquaticus sp. strain UV5, isolate...
100053   56159      Comparative genomics analysis of 102 Leptospir...
         56640      Comparative genomics analysis of 102 Leptospir...
         56643      Comparative genomics analysis of 102 Leptospir...
...                                                               ...
999894   HyVt-483   This is the collection of metagenome-assembled...
         S95        The genome sequncing and analysis of Thermosul...
999898   CEB3       Strain CEB3 is an acidophilic sulfate reducing...
999931   39T        A genomic analysis study presents the whole-ge...
         DSM 24617  Sequencing of Actinobacteria genome as a plant...

                                 additional_metadata
taxon_id strain
100      DSM 101                                 NaN
         UV5                                     NaN
100053   56159                                   NaN
         56640               collected_by:Jincai Qin
         56643               collected_by:Jincai Qin
...                                              ...
999894   HyVt-483   sample_type:metagenomic assembly
         S95                                     NaN
999898   CEB3             sample_type:whole organism
999931   39T                                     NaN
         DSM 24617                               NaN

[912435 rows x 66 columns]

In [4]:
df_unique_assemblies_refseq = pd.read_csv("refseq_representative_assemblies.csv",dtype=str)

In [5]:
df_unique_assemblies_patric = pd.read_csv("patric_representative_assemblies.csv",dtype=str)

In [6]:
# Rename columns in the final result
df_unique_assemblies_refseq = df_unique_assemblies_refseq.rename(columns={'taxid': 'taxon_id', 'infraspecific_name': 'strain'})

# The result will now have 'taxon_id' and 'strain' as column names
df_unique_assemblies_refseq

,taxon_id,strain,#assembly_accession,bioproject,biosample,wgs_master,refseq_category,taxid.1,species_taxid,organism_name,...,replicon_count,scaffold_count,contig_count,annotation_provider,annotation_name,annotation_date,total_gene_count,protein_coding_gene_count,non_coding_gene_count,pubmed_id
0,100,strain=DSM 101,GCF_004339465.1,PRJNA224116,SAMN10866377,SMFY00000000.1,reference genome,100,100,Ancylobacter aquaticus,...,0,11,11,NCBI RefSeq,GCF_004339465.1-RS_2024_05_01,2024-05-01,4513,4381,53,na
1,100053,strain=56159,GCF_002009835.1,PRJNA224116,SAMN02947886,JQGT00000000.1,na,100053,100053,Leptospira alexanderi,...,0,337,337,NCBI RefSeq,GCF_002009835.1-RS_2024_07_26,2024-07-26,3803,3490,44,na
2,100053,strain=56640,GCF_002009825.1,PRJNA224116,SAMN02947769,JQGV00000000.1,na,100053,100053,Leptospira alexanderi,...,0,368,368,NCBI RefSeq,GCF_002009825.1-RS_2024_05_19,2024-05-19,3815,3462,46,na
3,100053,strain=56643,GCF_002009805.1,PRJNA224116,SAMN02947770,JQGU00000000.1,na,100053,100053,Leptospira alexanderi,...,0,335,335,NCBI RefSeq,GCF_002009805.1-RS_2024_07_26,2024-07-26,3786,3467,44,na
4,100053,strain=56650,GCF_002009775.1,PRJNA224116,SAMN02947771,JQGS00000000.1,na,100053,100053,Leptospira alexanderi,...,0,341,341,NCBI RefSeq,GCF_002009775.1-RS_2024_05_19,2024-05-19,3788,3476,42,na
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
353843,999892,strain=P08,GCF_000204235.1,PRJNA224116,SAMN02471992,AFAM00000000.1,reference genome,999892,2559073,Cutibacterium modestum P08,...,0,22,22,NCBI RefSeq,GCF_000204235.1-RS_2024_03_28,2024-03-28,2500,2214,53,21571999
353844,999894,strain=S95,GCF_001652585.1,PRJNA224116,SAMN04623574,LWLG00000000.1,reference genome,999894,999894,Thermosulfurimonas dismutans,...,0,61,61,NCBI RefSeq,GCF_001652585.1-RS_2024_04_21,2024-04-21,2152,2077,55,na
353845,999931,strain=39T,GCF_910573815.1,PRJNA224116,SAMEA8751438,CAJTBP000000000.1,na,999931,999931,Barrientosiimonas humi,...,0,2,2,NCBI RefSeq,GCF_910573815.1-RS_2024_03_29,2024-03-29,3390,3319,56,na
353846,999931,strain=DSM 24617,GCF_006716095.1,PRJNA224116,SAMN11512942,VFOK00000000.1,reference genome,999931,999931,Barrientosiimonas humi,...,0,2,2,NCBI RefSeq,GCF_006716095.1-RS_2024_03_29,2024-03-29,3422,3354,56,na
353847,999931,strain=WGS1921,GCF_043161945.1,PRJNA224116,SAMN43971778,na,na,999931,999931,Barrientosiimonas humi,...,2,2,2,NCBI RefSeq,GCF_043161945.1-RS_2024_10_16,2024-10-16,3403,3308,57,na

In [7]:
# Remove "strain=" from every value in the 'strain' column
df_unique_assemblies_refseq['strain'] = df_unique_assemblies_refseq['strain'].str.replace('strain=', '', regex=False)

# The result will have "strain=" removed from the 'strain' column
df_unique_assemblies_refseq

,taxon_id,strain,#assembly_accession,bioproject,biosample,wgs_master,refseq_category,taxid.1,species_taxid,organism_name,...,replicon_count,scaffold_count,contig_count,annotation_provider,annotation_name,annotation_date,total_gene_count,protein_coding_gene_count,non_coding_gene_count,pubmed_id
0,100,DSM 101,GCF_004339465.1,PRJNA224116,SAMN10866377,SMFY00000000.1,reference genome,100,100,Ancylobacter aquaticus,...,0,11,11,NCBI RefSeq,GCF_004339465.1-RS_2024_05_01,2024-05-01,4513,4381,53,na
1,100053,56159,GCF_002009835.1,PRJNA224116,SAMN02947886,JQGT00000000.1,na,100053,100053,Leptospira alexanderi,...,0,337,337,NCBI RefSeq,GCF_002009835.1-RS_2024_07_26,2024-07-26,3803,3490,44,na
2,100053,56640,GCF_002009825.1,PRJNA224116,SAMN02947769,JQGV00000000.1,na,100053,100053,Leptospira alexanderi,...,0,368,368,NCBI RefSeq,GCF_002009825.1-RS_2024_05_19,2024-05-19,3815,3462,46,na
3,100053,56643,GCF_002009805.1,PRJNA224116,SAMN02947770,JQGU00000000.1,na,100053,100053,Leptospira alexanderi,...,0,335,335,NCBI RefSeq,GCF_002009805.1-RS_2024_07_26,2024-07-26,3786,3467,44,na
4,100053,56650,GCF_002009775.1,PRJNA224116,SAMN02947771,JQGS00000000.1,na,100053,100053,Leptospira alexanderi,...,0,341,341,NCBI RefSeq,GCF_002009775.1-RS_2024_05_19,2024-05-19,3788,3476,42,na
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
353843,999892,P08,GCF_000204235.1,PRJNA224116,SAMN02471992,AFAM00000000.1,reference genome,999892,2559073,Cutibacterium modestum P08,...,0,22,22,NCBI RefSeq,GCF_000204235.1-RS_2024_03_28,2024-03-28,2500,2214,53,21571999
353844,999894,S95,GCF_001652585.1,PRJNA224116,SAMN04623574,LWLG00000000.1,reference genome,999894,999894,Thermosulfurimonas dismutans,...,0,61,61,NCBI RefSeq,GCF_001652585.1-RS_2024_04_21,2024-04-21,2152,2077,55,na
353845,999931,39T,GCF_910573815.1,PRJNA224116,SAMEA8751438,CAJTBP000000000.1,na,999931,999931,Barrientosiimonas humi,...,0,2,2,NCBI RefSeq,GCF_910573815.1-RS_2024_03_29,2024-03-29,3390,3319,56,na
353846,999931,DSM 24617,GCF_006716095.1,PRJNA224116,SAMN11512942,VFOK00000000.1,reference genome,999931,999931,Barrientosiimonas humi,...,0,2,2,NCBI RefSeq,GCF_006716095.1-RS_2024_03_29,2024-03-29,3422,3354,56,na
353847,999931,WGS1921,GCF_043161945.1,PRJNA224116,SAMN43971778,na,na,999931,999931,Barrientosiimonas humi,...,2,2,2,NCBI RefSeq,GCF_043161945.1-RS_2024_10_16,2024-10-16,3403,3308,57,na

In [82]:
df_unique_assemblies_patric.columns

Index(['taxon_id', 'strain', 'genome_id', 'genome_name', 'organism_name',
       'taxon_id.1', 'genome_status', 'strain.1', 'serovar', 'biovar',
       'pathovar', 'mlst', 'other_typing', 'culture_collection', 'type_strain',
       'completion_date', 'publication', 'bioproject_accession',
       'biosample_accession', 'assembly_accession', 'genbank_accessions',
       'refseq_accessions', 'sequencing_centers', 'sequencing_status',
       'sequencing_platform', 'sequencing_depth', 'assembly_method',
       'chromosomes', 'plasmids', 'contigs', 'sequences', 'genome_length',
       'gc_content', 'patric_cds', 'brc1_cds', 'refseq_cds', 'isolation_site',
       'isolation_source', 'isolation_comments', 'collection_date',
       'isolation_country', 'geographic_location', 'latitude', 'longitude',
       'altitude', 'depth', 'other_environmental', 'host_name', 'host_gender',
       'host_age', 'host_health', 'body_sample_site', 'body_sample_subsite',
       'other_clinical', 'antimicrobial_resistance',
       'antimicrobial_resistance_evidence', 'gram_stain', 'cell_shape',
       'motility', 'sporulation', 'temperature_range', 'optimal_temperature',
       'salinity', 'oxygen_requirement', 'habitat', 'disease', 'comments',
       'additional_metadata'],
      dtype='object')

In [8]:
# Rename the index levels to 'name1' and 'name2'
df_patric_unique = df_unique_assemblies_patric.rename_axis(index={'taxon_id': 'name1', 'strain': 'name2'}).reset_index()
df_refseq_unique = df_unique_assemblies_refseq.rename_axis(index={'taxon_id': 'name1', 'strain': 'name2'}).reset_index()
# Assuming the two DataFrames are df1 and df2
common_taxon_strain = pd.merge(df_patric_unique[['taxon_id', 'strain']], df_refseq_unique[['taxon_id', 'strain']], 
                                on=['taxon_id', 'strain'], how='inner')

# The result will contain the common unique combinations of 'taxon_id' and 'strain'
common_taxon_strain

       taxon_id     strain
0           100    DSM 101
1        100053      56159
2        100053      56640
3        100053      56643
4        100053      56650
...         ...        ...
295050   999891      TA208
295051   999892        P08
295052   999894        S95
295053   999931        39T
295054   999931  DSM 24617

[295055 rows x 2 columns]

In [9]:
# Perform the merge, keeping 'genome_id' from patric and 'ftp_path' from refseq
common_taxon_strain = pd.merge(
    df_patric_unique[['taxon_id', 'strain', 'genome_id','contigs']], 
    df_refseq_unique[['taxon_id', 'strain', 'ftp_path','contig_count']], 
    on=['taxon_id', 'strain'], 
    how='inner'
)

# The result will contain the common unique combinations of 'taxon_id' and 'strain'
# along with 'genome_id' from patric and 'ftp_path' from refseq
# Rename the 'contigs' column to 'contigs_patric'
common_taxon_strain = common_taxon_strain.rename(columns={'contigs': 'contigs_patric'})

# The result will have the 'contigs' column renamed to 'contigs_patric'
common_taxon_strain

,taxon_id,strain,genome_id,contigs_patric,ftp_path,contig_count
0,100,DSM 101,100.11,11,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,11
1,100053,56159,100053.7,337,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,337
2,100053,56640,100053.6,368,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,368
3,100053,56643,100053.5,335,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,335
4,100053,56650,100053.4,341,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,341
...,...,...,...,...,...,...
295050,999891,TA208,999891.3,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1
295051,999892,P08,999892.3,22,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,22
295052,999894,S95,999894.9,61,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,61
295053,999931,39T,999931.5,2,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/9...,2
295054,999931,DSM 24617,999931.3,2,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,2

In [23]:
# First DataFrame where contigs_patric = "1" and contig_count = "1"
df_contigs_one = common_taxon_strain[(common_taxon_strain['contigs_patric'] == "10") & 
                                     (common_taxon_strain['contig_count'] == "10")]

# Second DataFrame containing the remaining rows
df_remaining = common_taxon_strain[~((common_taxon_strain['contigs_patric'] == "10") & 
                                     (common_taxon_strain['contig_count'] == "10"))]

# df_contigs_one contains rows where contigs_patric = "1" and contig_count = "1"
# df_remaining contains the remaining rows
df_contigs_one

,taxon_id,strain,genome_id,contigs_patric,ftp_path,contig_count
28,1001583,KB290,1001583.3,10,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,10
89,1002227,VKM B-2663,1002227.6,10,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,10
772,1017270,NIO-1003,1017270.12,10,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/9...,10
1021,1034769,HW567,1034769.3,10,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,10
1052,1036177,NC8,1036177.3,10,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,10
...,...,...,...,...,...,...
294244,985002,CFSA17SA054,985002.353,10,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,10
294615,992037,Hp A-20,992037.3,10,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,10
295017,999423,F0473,999423.3,10,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,10
295037,999544,DSM 45548,999544.3,10,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,10
295047,999628,EHg5,999628.3,10,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,10

In [24]:
df_contigs_one.to_csv("genomes.csv")

In [89]:
df_remaining.to_csv("common_strains_with_multiple_contigs.csv")
df_contigs_one.to_csv("common_strains_with_one_contig.csv")

In [90]:
df_remaining

,taxon_id,strain,genome_id,contigs_patric,ftp_path,contig_count
0,100,DSM 101,100.11,11,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,11
1,100053,56159,100053.7,337,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,337
2,100053,56640,100053.6,368,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,368
3,100053,56643,100053.5,335,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,335
4,100053,56650,100053.4,341,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,341
...,...,...,...,...,...,...
295049,999700,"JA576,NBRC 108863,KCTC 15144",999700.3,69,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,69
295051,999892,P08,999892.3,22,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,22
295052,999894,S95,999894.9,61,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,61
295053,999931,39T,999931.5,2,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/9...,2
295054,999931,DSM 24617,999931.3,2,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,2

In [26]:
import pandas as pd
df = pd.read_csv("/Users/gboldirev1/1contig/output_file.csv",dtype=str)
df

,col1,col2,col3,col4,col5,col6,col7,query_fna,subject_fna,query_length,...,n_of_-1,n_of_0,n_of_1,n_of_2,n_of_3,n_of_4,n_of_5,n_of_6,n_of_7,binary_filename
0,25,1001534,TI0902,1001534.3,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,1001534.3.fna,GCF_000248435.2_ASM24843v2_genomic.fna,1892744,...,20,312,1868316,0,25,53,24129,0,0,1001534_subject_array_1739113446.bin
1,26,1001542,TIGB03,1001542.3,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,1001542.3.fna,GCF_000248415.2_ASM24841v2_genomic.fna,1968651,...,16,0,1968488,0,23,52,29,0,0,1001542_subject_array_1739113448.bin
2,29,1001585,NK-01,1001585.3,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,1001585.3.fna,GCF_000204295.1_ASM20429v1_genomic.fna,5434353,...,0,0,5434353,0,0,0,0,0,0,1001585_subject_array_1739113452.bin
3,92,100226,CFB_NBC_0001,100226.137,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,100226.137.fna,GCF_008931305.1_ASM893130v1_genomic.fna,8667664,...,0,0,8667664,0,0,0,0,0,0,100226_subject_array_1739113458.bin
4,103,1002672,IMCC9063,1002672.3,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,1002672.3.fna,GCF_000195085.1_ASM19508v1_genomic.fna,1284727,...,0,0,1284727,0,0,0,0,0,0,1002672_subject_array_1739113459.bin
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20646,294973,99822,DB60705-15,99822.28,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,99822.28.fna,GCF_009650275.1_ASM965027v1_genomic.fna,2190656,...,0,99,2190557,0,0,0,0,0,0,99822_subject_array_1739184665.bin
20647,294975,99822,NCTC4669,99822.25,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/9...,1,99822.25.fna,GCF_900635345.1_41686_B01_genomic.fna,2201894,...,0,0,2201894,0,0,0,0,0,0,99822_subject_array_1739184667.bin
20648,294989,99822,STREP97-15,99822.29,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,99822.29.fna,GCF_009650295.1_ASM965029v1_genomic.fna,2432570,...,0,99,2432471,0,0,0,0,0,0,99822_subject_array_1739184669.bin
20649,294996,999183,DSM 25104,999183.3,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,999183.3.fna,GCF_029625435.1_ASM2962543v1_genomic.fna,1873758,...,0,0,1873758,0,0,0,0,0,0,999183_subject_array_1739184670.bin
20650,295050,999891,TA208,999891.3,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,999891.3.fna,GCF_000195515.1_ASM19551v1_genomic.fna,3937511,...,0,0,3937511,0,0,0,0,0,0,999891_subject_array_1739184673.bin

In [11]:
df1 = pd.read_csv("/Users/gboldirev1/genome_metadata",sep='\t',dtype=str)
df1
df2 = pd.read_csv("/Users/gboldirev1/assembly_summary.txt",sep='\t',dtype=str,skiprows=1)

In [13]:
merged_df = pd.merge(df, df2, left_on='col6', right_on='ftp_path', how='inner')

,col1,col2,col3,col4,col5,col6,col7,query_fna,subject_fna,query_length,...,replicon_count,scaffold_count,contig_count,annotation_provider,annotation_name,annotation_date,total_gene_count,protein_coding_gene_count,non_coding_gene_count,pubmed_id
0,25,1001534,TI0902,1001534.3,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,1001534.3.fna,GCF_000248435.2_ASM24843v2_genomic.fna,1892744,...,1,1,1,NCBI RefSeq,NCBI Prokaryotic Genome Annotation Pipeline (P...,2024-03-05,1950,1736,52,22535949
1,26,1001542,TIGB03,1001542.3,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,1001542.3.fna,GCF_000248415.2_ASM24841v2_genomic.fna,1968651,...,1,1,1,NCBI RefSeq,GCF_000248415.2-RS_2024_03_27,2024-03-27,2040,1823,53,22535949
2,29,1001585,NK-01,1001585.3,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,1001585.3.fna,GCF_000204295.1_ASM20429v1_genomic.fna,5434353,...,1,1,1,NCBI RefSeq,GCF_000204295.1-RS_2024_10_21,2024-10-21,5115,5002,82,21551299
3,92,100226,CFB_NBC_0001,100226.137,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,100226.137.fna,GCF_008931305.1_ASM893130v1_genomic.fna,8667664,...,1,1,1,NCBI RefSeq,GCF_008931305.1-RS_2024_03_22,2024-03-22,7853,7582,87,31548381
4,103,1002672,IMCC9063,1002672.3,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,1002672.3.fna,GCF_000195085.1_ASM19508v1_genomic.fna,1284727,...,1,1,1,NCBI RefSeq,GCF_000195085.1-RS_2024_03_31,2024-03-31,1434,1385,38,21515764
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20646,294973,99822,DB60705-15,99822.28,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,99822.28.fna,GCF_009650275.1_ASM965027v1_genomic.fna,2190656,...,1,1,1,NCBI RefSeq,GCF_009650275.1-RS_2024_05_06,2024-05-06,2162,1994,91,na
20647,294975,99822,NCTC4669,99822.25,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/9...,1,99822.25.fna,GCF_900635345.1_41686_B01_genomic.fna,2201894,...,1,1,1,NCBI RefSeq,NCBI Prokaryotic Genome Annotation Pipeline (P...,2024-02-13,2218,2011,89,na
20648,294989,99822,STREP97-15,99822.29,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,99822.29.fna,GCF_009650295.1_ASM965029v1_genomic.fna,2432570,...,1,1,1,NCBI RefSeq,GCF_009650295.1-RS_2024_05_06,2024-05-06,2486,2277,90,na
20649,294996,999183,DSM 25104,999183.3,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,999183.3.fna,GCF_029625435.1_ASM2962543v1_genomic.fna,1873758,...,1,1,1,NCBI RefSeq,GCF_029625435.1-RS_2024_04_08,2024-04-08,1691,1621,61,na
20650,295050,999891,TA208,999891.3,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,999891.3.fna,GCF_000195515.1_ASM19551v1_genomic.fna,3937511,...,1,1,1,NCBI RefSeq,GCF_000195515.1-RS_2024_03_27,2024-03-27,4082,3885,93,21515778

In [16]:
filtered_df = merged_df[merged_df['assembly_level'] == 'Complete Genome']
filtered_df

,col1,col2,col3,col4,col5,col6,col7,query_fna,subject_fna,query_length,...,replicon_count,scaffold_count,contig_count,annotation_provider,annotation_name,annotation_date,total_gene_count,protein_coding_gene_count,non_coding_gene_count,pubmed_id
0,25,1001534,TI0902,1001534.3,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,1001534.3.fna,GCF_000248435.2_ASM24843v2_genomic.fna,1892744,...,1,1,1,NCBI RefSeq,NCBI Prokaryotic Genome Annotation Pipeline (P...,2024-03-05,1950,1736,52,22535949
1,26,1001542,TIGB03,1001542.3,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,1001542.3.fna,GCF_000248415.2_ASM24841v2_genomic.fna,1968651,...,1,1,1,NCBI RefSeq,GCF_000248415.2-RS_2024_03_27,2024-03-27,2040,1823,53,22535949
2,29,1001585,NK-01,1001585.3,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,1001585.3.fna,GCF_000204295.1_ASM20429v1_genomic.fna,5434353,...,1,1,1,NCBI RefSeq,GCF_000204295.1-RS_2024_10_21,2024-10-21,5115,5002,82,21551299
3,92,100226,CFB_NBC_0001,100226.137,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,100226.137.fna,GCF_008931305.1_ASM893130v1_genomic.fna,8667664,...,1,1,1,NCBI RefSeq,GCF_008931305.1-RS_2024_03_22,2024-03-22,7853,7582,87,31548381
4,103,1002672,IMCC9063,1002672.3,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,1002672.3.fna,GCF_000195085.1_ASM19508v1_genomic.fna,1284727,...,1,1,1,NCBI RefSeq,GCF_000195085.1-RS_2024_03_31,2024-03-31,1434,1385,38,21515764
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20642,294969,99807,DSM 44609,99807.17,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,99807.17.fna,GCF_030408435.1_ASM3040843v1_genomic.fna,2599172,...,1,1,1,NCBI RefSeq,GCF_030408435.1-RS_2024_07_07,2024-07-07,2206,2101,62,na
20643,294970,998088,B565,998088.4,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,998088.4.fna,GCF_000204115.1_ASM20411v1_genomic.fna,4551783,...,1,1,1,NCBI RefSeq,GCF_000204115.1-RS_2024_03_20,2024-03-20,4201,4032,139,21551296
20647,294975,99822,NCTC4669,99822.25,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/9...,1,99822.25.fna,GCF_900635345.1_41686_B01_genomic.fna,2201894,...,1,1,1,NCBI RefSeq,NCBI Prokaryotic Genome Annotation Pipeline (P...,2024-02-13,2218,2011,89,na
20649,294996,999183,DSM 25104,999183.3,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,999183.3.fna,GCF_029625435.1_ASM2962543v1_genomic.fna,1873758,...,1,1,1,NCBI RefSeq,GCF_029625435.1-RS_2024_04_08,2024-04-08,1691,1621,61,na
20650,295050,999891,TA208,999891.3,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,999891.3.fna,GCF_000195515.1_ASM19551v1_genomic.fna,3937511,...,1,1,1,NCBI RefSeq,GCF_000195515.1-RS_2024_03_27,2024-03-27,4082,3885,93,21515778

In [17]:
merged_d = pd.merge(df, df1, left_on='col4', right_on='genome_id', how='inner')
merged_d

,col1,col2,col3,col4,col5,col6,col7,query_fna,subject_fna,query_length,...,motility,sporulation,temperature_range,optimal_temperature,salinity,oxygen_requirement,habitat,disease,comments,additional_metadata
0,25,1001534,TI0902,1001534.3,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,1001534.3.fna,GCF_000248435.2_ASM24843v2_genomic.fna,1892744,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Francisella tularensis TI0902.This strain will...,NaN
1,26,1001542,TIGB03,1001542.3,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,1001542.3.fna,GCF_000248415.2_ASM24841v2_genomic.fna,1968651,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Francisella tularensis TIGB03.This strain is a...,NaN
2,29,1001585,NK-01,1001585.3,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,1001585.3.fna,GCF_000204295.1_ASM20429v1_genomic.fna,5434353,...,NaN,NaN,NaN,-,NaN,NaN,NaN,NaN,This strain will be used for comparative analy...,NaN
3,92,100226,CFB_NBC_0001,100226.137,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,100226.137.fna,GCF_008931305.1_ASM893130v1_genomic.fna,8667664,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Genome sequencing of Streptomyces coelicolor C...,sample_type:cell culture
4,103,1002672,IMCC9063,1002672.3,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,1002672.3.fna,GCF_000195085.1_ASM19508v1_genomic.fna,1284727,...,NaN,NaN,NaN,-,NaN,NaN,NaN,NaN,Genomic DNA from Strain IMCC9063 from SAR11 gr...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20646,294973,99822,DB60705-15,99822.28,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,99822.28.fna,GCF_009650275.1_ASM965027v1_genomic.fna,2190656,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Comparative Genomic Analysis of the Streptococ...,collected_by:SGH
20647,294975,99822,NCTC4669,99822.25,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/9...,1,99822.25.fna,GCF_900635345.1_41686_B01_genomic.fna,2201894,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.sanger.ac.uk/resources/downloads/ba...,NaN
20648,294989,99822,STREP97-15,99822.29,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,99822.29.fna,GCF_009650295.1_ASM965029v1_genomic.fna,2432570,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Comparative Genomic Analysis of the Streptococ...,collected_by:SGH
20649,294996,999183,DSM 25104,999183.3,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,999183.3.fna,GCF_029625435.1_ASM2962543v1_genomic.fna,1873758,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sample_type:bacterial isolate;collected_by:Ell...
20650,295050,999891,TA208,999891.3,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,999891.3.fna,GCF_000195515.1_ASM19551v1_genomic.fna,3937511,...,NaN,NaN,NaN,-,NaN,NaN,NaN,NaN,No description available.,NaN

In [19]:
df_c = merged_d[merged_d['genome_status'] == 'Complete']
df_c

,col1,col2,col3,col4,col5,col6,col7,query_fna,subject_fna,query_length,...,motility,sporulation,temperature_range,optimal_temperature,salinity,oxygen_requirement,habitat,disease,comments,additional_metadata
0,25,1001534,TI0902,1001534.3,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,1001534.3.fna,GCF_000248435.2_ASM24843v2_genomic.fna,1892744,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Francisella tularensis TI0902.This strain will...,NaN
1,26,1001542,TIGB03,1001542.3,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,1001542.3.fna,GCF_000248415.2_ASM24841v2_genomic.fna,1968651,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Francisella tularensis TIGB03.This strain is a...,NaN
2,29,1001585,NK-01,1001585.3,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,1001585.3.fna,GCF_000204295.1_ASM20429v1_genomic.fna,5434353,...,NaN,NaN,NaN,-,NaN,NaN,NaN,NaN,This strain will be used for comparative analy...,NaN
3,92,100226,CFB_NBC_0001,100226.137,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,100226.137.fna,GCF_008931305.1_ASM893130v1_genomic.fna,8667664,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Genome sequencing of Streptomyces coelicolor C...,sample_type:cell culture
4,103,1002672,IMCC9063,1002672.3,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,1002672.3.fna,GCF_000195085.1_ASM19508v1_genomic.fna,1284727,...,NaN,NaN,NaN,-,NaN,NaN,NaN,NaN,Genomic DNA from Strain IMCC9063 from SAR11 gr...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20646,294973,99822,DB60705-15,99822.28,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,99822.28.fna,GCF_009650275.1_ASM965027v1_genomic.fna,2190656,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Comparative Genomic Analysis of the Streptococ...,collected_by:SGH
20647,294975,99822,NCTC4669,99822.25,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/9...,1,99822.25.fna,GCF_900635345.1_41686_B01_genomic.fna,2201894,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.sanger.ac.uk/resources/downloads/ba...,NaN
20648,294989,99822,STREP97-15,99822.29,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,99822.29.fna,GCF_009650295.1_ASM965029v1_genomic.fna,2432570,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Comparative Genomic Analysis of the Streptococ...,collected_by:SGH
20649,294996,999183,DSM 25104,999183.3,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,999183.3.fna,GCF_029625435.1_ASM2962543v1_genomic.fna,1873758,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sample_type:bacterial isolate;collected_by:Ell...
20650,295050,999891,TA208,999891.3,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,999891.3.fna,GCF_000195515.1_ASM19551v1_genomic.fna,3937511,...,NaN,NaN,NaN,-,NaN,NaN,NaN,NaN,No description available.,NaN

In [21]:
df_c

,col1,col2,col3,col4,col5,col6,col7,query_fna,subject_fna,query_length,...,motility,sporulation,temperature_range,optimal_temperature,salinity,oxygen_requirement,habitat,disease,comments,additional_metadata
0,25,1001534,TI0902,1001534.3,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,1001534.3.fna,GCF_000248435.2_ASM24843v2_genomic.fna,1892744,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Francisella tularensis TI0902.This strain will...,NaN
1,26,1001542,TIGB03,1001542.3,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,1001542.3.fna,GCF_000248415.2_ASM24841v2_genomic.fna,1968651,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Francisella tularensis TIGB03.This strain is a...,NaN
2,29,1001585,NK-01,1001585.3,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,1001585.3.fna,GCF_000204295.1_ASM20429v1_genomic.fna,5434353,...,NaN,NaN,NaN,-,NaN,NaN,NaN,NaN,This strain will be used for comparative analy...,NaN
3,92,100226,CFB_NBC_0001,100226.137,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,100226.137.fna,GCF_008931305.1_ASM893130v1_genomic.fna,8667664,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Genome sequencing of Streptomyces coelicolor C...,sample_type:cell culture
4,103,1002672,IMCC9063,1002672.3,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,1002672.3.fna,GCF_000195085.1_ASM19508v1_genomic.fna,1284727,...,NaN,NaN,NaN,-,NaN,NaN,NaN,NaN,Genomic DNA from Strain IMCC9063 from SAR11 gr...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20646,294973,99822,DB60705-15,99822.28,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,99822.28.fna,GCF_009650275.1_ASM965027v1_genomic.fna,2190656,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Comparative Genomic Analysis of the Streptococ...,collected_by:SGH
20647,294975,99822,NCTC4669,99822.25,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/9...,1,99822.25.fna,GCF_900635345.1_41686_B01_genomic.fna,2201894,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.sanger.ac.uk/resources/downloads/ba...,NaN
20648,294989,99822,STREP97-15,99822.29,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,99822.29.fna,GCF_009650295.1_ASM965029v1_genomic.fna,2432570,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Comparative Genomic Analysis of the Streptococ...,collected_by:SGH
20649,294996,999183,DSM 25104,999183.3,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,999183.3.fna,GCF_029625435.1_ASM2962543v1_genomic.fna,1873758,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sample_type:bacterial isolate;collected_by:Ell...
20650,295050,999891,TA208,999891.3,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,999891.3.fna,GCF_000195515.1_ASM19551v1_genomic.fna,3937511,...,NaN,NaN,NaN,-,NaN,NaN,NaN,NaN,No description available.,NaN

In [22]:
filtered_df

,col1,col2,col3,col4,col5,col6,col7,query_fna,subject_fna,query_length,...,replicon_count,scaffold_count,contig_count,annotation_provider,annotation_name,annotation_date,total_gene_count,protein_coding_gene_count,non_coding_gene_count,pubmed_id
0,25,1001534,TI0902,1001534.3,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,1001534.3.fna,GCF_000248435.2_ASM24843v2_genomic.fna,1892744,...,1,1,1,NCBI RefSeq,NCBI Prokaryotic Genome Annotation Pipeline (P...,2024-03-05,1950,1736,52,22535949
1,26,1001542,TIGB03,1001542.3,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,1001542.3.fna,GCF_000248415.2_ASM24841v2_genomic.fna,1968651,...,1,1,1,NCBI RefSeq,GCF_000248415.2-RS_2024_03_27,2024-03-27,2040,1823,53,22535949
2,29,1001585,NK-01,1001585.3,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,1001585.3.fna,GCF_000204295.1_ASM20429v1_genomic.fna,5434353,...,1,1,1,NCBI RefSeq,GCF_000204295.1-RS_2024_10_21,2024-10-21,5115,5002,82,21551299
3,92,100226,CFB_NBC_0001,100226.137,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,100226.137.fna,GCF_008931305.1_ASM893130v1_genomic.fna,8667664,...,1,1,1,NCBI RefSeq,GCF_008931305.1-RS_2024_03_22,2024-03-22,7853,7582,87,31548381
4,103,1002672,IMCC9063,1002672.3,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,1002672.3.fna,GCF_000195085.1_ASM19508v1_genomic.fna,1284727,...,1,1,1,NCBI RefSeq,GCF_000195085.1-RS_2024_03_31,2024-03-31,1434,1385,38,21515764
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20642,294969,99807,DSM 44609,99807.17,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,99807.17.fna,GCF_030408435.1_ASM3040843v1_genomic.fna,2599172,...,1,1,1,NCBI RefSeq,GCF_030408435.1-RS_2024_07_07,2024-07-07,2206,2101,62,na
20643,294970,998088,B565,998088.4,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,998088.4.fna,GCF_000204115.1_ASM20411v1_genomic.fna,4551783,...,1,1,1,NCBI RefSeq,GCF_000204115.1-RS_2024_03_20,2024-03-20,4201,4032,139,21551296
20647,294975,99822,NCTC4669,99822.25,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/9...,1,99822.25.fna,GCF_900635345.1_41686_B01_genomic.fna,2201894,...,1,1,1,NCBI RefSeq,NCBI Prokaryotic Genome Annotation Pipeline (P...,2024-02-13,2218,2011,89,na
20649,294996,999183,DSM 25104,999183.3,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,999183.3.fna,GCF_029625435.1_ASM2962543v1_genomic.fna,1873758,...,1,1,1,NCBI RefSeq,GCF_029625435.1-RS_2024_04_08,2024-04-08,1691,1621,61,na
20650,295050,999891,TA208,999891.3,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,999891.3.fna,GCF_000195515.1_ASM19551v1_genomic.fna,3937511,...,1,1,1,NCBI RefSeq,GCF_000195515.1-RS_2024_03_27,2024-03-27,4082,3885,93,21515778

In [ ]:
results = pd.merge(df_c, filtered_df, on='col6', how='inner')
results.to_csv("complete_labeled_genomes.csv")

In [29]:
results

,col1_x,col2_x,col3_x,col4_x,col5_x,col6,col7_x,query_fna_x,subject_fna_x,query_length_x,...,replicon_count,scaffold_count,contig_count,annotation_provider,annotation_name,annotation_date,total_gene_count,protein_coding_gene_count,non_coding_gene_count,pubmed_id
0,25,1001534,TI0902,1001534.3,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,1001534.3.fna,GCF_000248435.2_ASM24843v2_genomic.fna,1892744,...,1,1,1,NCBI RefSeq,NCBI Prokaryotic Genome Annotation Pipeline (P...,2024-03-05,1950,1736,52,22535949
1,26,1001542,TIGB03,1001542.3,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,1001542.3.fna,GCF_000248415.2_ASM24841v2_genomic.fna,1968651,...,1,1,1,NCBI RefSeq,GCF_000248415.2-RS_2024_03_27,2024-03-27,2040,1823,53,22535949
2,29,1001585,NK-01,1001585.3,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,1001585.3.fna,GCF_000204295.1_ASM20429v1_genomic.fna,5434353,...,1,1,1,NCBI RefSeq,GCF_000204295.1-RS_2024_10_21,2024-10-21,5115,5002,82,21551299
3,92,100226,CFB_NBC_0001,100226.137,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,100226.137.fna,GCF_008931305.1_ASM893130v1_genomic.fna,8667664,...,1,1,1,NCBI RefSeq,GCF_008931305.1-RS_2024_03_22,2024-03-22,7853,7582,87,31548381
4,103,1002672,IMCC9063,1002672.3,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,1002672.3.fna,GCF_000195085.1_ASM19508v1_genomic.fna,1284727,...,1,1,1,NCBI RefSeq,GCF_000195085.1-RS_2024_03_31,2024-03-31,1434,1385,38,21515764
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15941,294969,99807,DSM 44609,99807.17,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,99807.17.fna,GCF_030408435.1_ASM3040843v1_genomic.fna,2599172,...,1,1,1,NCBI RefSeq,GCF_030408435.1-RS_2024_07_07,2024-07-07,2206,2101,62,na
15942,294970,998088,B565,998088.4,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,998088.4.fna,GCF_000204115.1_ASM20411v1_genomic.fna,4551783,...,1,1,1,NCBI RefSeq,GCF_000204115.1-RS_2024_03_20,2024-03-20,4201,4032,139,21551296
15943,294975,99822,NCTC4669,99822.25,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/9...,1,99822.25.fna,GCF_900635345.1_41686_B01_genomic.fna,2201894,...,1,1,1,NCBI RefSeq,NCBI Prokaryotic Genome Annotation Pipeline (P...,2024-02-13,2218,2011,89,na
15944,294996,999183,DSM 25104,999183.3,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,999183.3.fna,GCF_029625435.1_ASM2962543v1_genomic.fna,1873758,...,1,1,1,NCBI RefSeq,GCF_029625435.1-RS_2024_04_08,2024-04-08,1691,1621,61,na
15945,295050,999891,TA208,999891.3,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,999891.3.fna,GCF_000195515.1_ASM19551v1_genomic.fna,3937511,...,1,1,1,NCBI RefSeq,GCF_000195515.1-RS_2024_03_27,2024-03-27,4082,3885,93,21515778

In [30]:
df

,col1,col2,col3,col4,col5,col6,col7,query_fna,subject_fna,query_length,...,n_of_-1,n_of_0,n_of_1,n_of_2,n_of_3,n_of_4,n_of_5,n_of_6,n_of_7,binary_filename
0,25,1001534,TI0902,1001534.3,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,1001534.3.fna,GCF_000248435.2_ASM24843v2_genomic.fna,1892744,...,20,312,1868316,0,25,53,24129,0,0,1001534_subject_array_1739113446.bin
1,26,1001542,TIGB03,1001542.3,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,1001542.3.fna,GCF_000248415.2_ASM24841v2_genomic.fna,1968651,...,16,0,1968488,0,23,52,29,0,0,1001542_subject_array_1739113448.bin
2,29,1001585,NK-01,1001585.3,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,1001585.3.fna,GCF_000204295.1_ASM20429v1_genomic.fna,5434353,...,0,0,5434353,0,0,0,0,0,0,1001585_subject_array_1739113452.bin
3,92,100226,CFB_NBC_0001,100226.137,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,100226.137.fna,GCF_008931305.1_ASM893130v1_genomic.fna,8667664,...,0,0,8667664,0,0,0,0,0,0,100226_subject_array_1739113458.bin
4,103,1002672,IMCC9063,1002672.3,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,1002672.3.fna,GCF_000195085.1_ASM19508v1_genomic.fna,1284727,...,0,0,1284727,0,0,0,0,0,0,1002672_subject_array_1739113459.bin
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20646,294973,99822,DB60705-15,99822.28,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,99822.28.fna,GCF_009650275.1_ASM965027v1_genomic.fna,2190656,...,0,99,2190557,0,0,0,0,0,0,99822_subject_array_1739184665.bin
20647,294975,99822,NCTC4669,99822.25,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/9...,1,99822.25.fna,GCF_900635345.1_41686_B01_genomic.fna,2201894,...,0,0,2201894,0,0,0,0,0,0,99822_subject_array_1739184667.bin
20648,294989,99822,STREP97-15,99822.29,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,99822.29.fna,GCF_009650295.1_ASM965029v1_genomic.fna,2432570,...,0,99,2432471,0,0,0,0,0,0,99822_subject_array_1739184669.bin
20649,294996,999183,DSM 25104,999183.3,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,999183.3.fna,GCF_029625435.1_ASM2962543v1_genomic.fna,1873758,...,0,0,1873758,0,0,0,0,0,0,999183_subject_array_1739184670.bin
20650,295050,999891,TA208,999891.3,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,999891.3.fna,GCF_000195515.1_ASM19551v1_genomic.fna,3937511,...,0,0,3937511,0,0,0,0,0,0,999891_subject_array_1739184673.bin

In [32]:
merged_results = pd.merge(results, df, on='col6', how='inner')
merged_results.to_csv("complete_labeled_genomes.csv")

In [33]:
df = pd.read_csv("/Users/gboldirev1/common_strains_with_multiple_contigs.csv",dtype=str)
df

,Unnamed: 0,taxon_id,strain,genome_id,contigs_patric,ftp_path,contig_count
0,0,100,DSM 101,100.11,11,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,11
1,1,100053,56159,100053.7,337,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,337
2,2,100053,56640,100053.6,368,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,368
3,3,100053,56643,100053.5,335,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,335
4,4,100053,56650,100053.4,341,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,341
...,...,...,...,...,...,...,...
273941,295049,999700,"JA576,NBRC 108863,KCTC 15144",999700.3,69,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,69
273942,295051,999892,P08,999892.3,22,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,22
273943,295052,999894,S95,999894.9,61,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,61
273944,295053,999931,39T,999931.5,2,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/9...,2
273945,295054,999931,DSM 24617,999931.3,2,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,2

In [34]:
import pandas as pd

# List of file paths
file_paths = [
    "/Users/gboldirev1/2ontigs/2to2results.csv",
    "/Users/gboldirev1/3contigs/output_file_3.csv",
    "/Users/gboldirev1/4contig/output_file_4.csv",
    "/Users/gboldirev1/5contigs/output_file_5.csv",
    "/Users/gboldirev1/6contgis/output_file_6.csv",
    "/Users/gboldirev1/7contigs/output_file_7.csv",
    "/Users/gboldirev1/8contig/output_file_8.csv",
    "/Users/gboldirev1/9contig/output_file_9.csv",
    "/Users/gboldirev1/10contig/output_file_10.csv"
]

# Load the main DataFrame
df = pd.read_csv("/Users/gboldirev1/common_strains_with_multiple_contigs.csv", dtype=str)

# Iterate over each file, find common 'ftp_path' values, and remove them
for file_path in file_paths:
    try:
        temp_df = pd.read_csv(file_path, dtype=str)  # Load the file
        if 'ftp_path' in temp_df.columns:  # Ensure 'ftp_path' column exists
            df = df[~df['ftp_path'].isin(temp_df['ftp_path'])]  # Remove common 'ftp_path'
    except FileNotFoundError:
        print(f"Warning: File not found - {file_path}")
    except Exception as e:
        print(f"Error processing {file_path}: {e}")

,Unnamed: 0,taxon_id,strain,genome_id,contigs_patric,ftp_path,contig_count
0,0,100,DSM 101,100.11,11,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,11
1,1,100053,56159,100053.7,337,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,337
2,2,100053,56640,100053.6,368,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,368
3,3,100053,56643,100053.5,335,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,335
4,4,100053,56650,100053.4,341,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,341
...,...,...,...,...,...,...,...
273941,295049,999700,"JA576,NBRC 108863,KCTC 15144",999700.3,69,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,69
273942,295051,999892,P08,999892.3,22,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,22
273943,295052,999894,S95,999894.9,61,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,61
273944,295053,999931,39T,999931.5,2,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/9...,2
273945,295054,999931,DSM 24617,999931.3,2,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,2

In [36]:
import pandas as pd

# List of file paths
file_paths = [
    "/Users/gboldirev1/2ontigs/2to2results.csv",
    "/Users/gboldirev1/3contigs/output_file_3.csv",
    "/Users/gboldirev1/4contig/output_file_4.csv",
    "/Users/gboldirev1/5contigs/output_file_5.csv",
    "/Users/gboldirev1/6contgis/output_file_6.csv",
    "/Users/gboldirev1/7contigs/output_file_7.csv",
    "/Users/gboldirev1/8contig/output_file_8.csv",
    "/Users/gboldirev1/9contig/output_file_9.csv",
    "/Users/gboldirev1/10contig/output_file_10.csv"
]

# Load the main DataFrame
df = pd.read_csv("/Users/gboldirev1/common_strains_with_multiple_contigs.csv", dtype=str)

# Iterate over each file, find common 'ftp_path' values, and remove them
for file_path in file_paths:
    try:
        temp_df = pd.read_csv(file_path, usecols=[5], dtype=str, header=None)  # Load only column 6
        temp_df.columns = ['ftp_path']  # Rename column for consistency
        df = df[~df['ftp_path'].isin(temp_df['ftp_path'])]  # Remove common ftp_path values
    except FileNotFoundError:
        print(f"Warning: File not found - {file_path}")
    except Exception as e:
        print(f"Error processing {file_path}: {e}")

df.to_csv("remaining_genomes.csv")