In [7]:
import pandas as pd

# Reset pandas display options back to normal first (optional, but safe)
pd.reset_option("display.max_rows")
pd.reset_option("display.max_columns")
pd.reset_option("display.width")
pd.reset_option("display.max_colwidth")

# Load file with no index column
Ensembl = pd.read_csv(
    "/Users/gboldirev1/Desktop/gboldirev1/species_EnsemblFungi.txt",
    sep="\t",
    index_col=False
)

# Fix the first column name
Ensembl = Ensembl.rename(columns={"#name": "name"})

# Show the DataFrame
Ensembl

,name,species,division,taxonomy_id,assembly,assembly_accession,genebuild,variation,microarray,pan_compara,peptide_compara,genome_alignments,other_alignments,core_db,species_id
0,[Candida] arabinofermentans NRRL YB-2248,_candida_arabinofermentans_nrrl_yb_2248_gca_00...,EnsemblFungi,983967,Canar1,GCA_001661425.1,2016-09-DOEJointGenomeInstitute,N,N,N,N,N,Y,fungi_ascomycota3_collection_core_61_114_1,192
1,[Candida] auris str. 6684,_candida_auris_gca_001189475,EnsemblFungi,498019,ASM118947v1,GCA_001189475.1,2015-08-IndianInstituteofScienceIISc,N,N,N,N,N,Y,fungi_ascomycota3_collection_core_61_114_1,44
2,[Candida] auris,_candida_auris_gca_002775015,EnsemblFungi,498019,Cand_auris_B11221_V1,GCA_002775015.1,2017-11-CentersforDiseaseControlandPrevention,N,N,N,N,N,Y,fungi_ascomycota3_collection_core_61_114_1,294
3,[Candida] auris,_candida_auris_gca_003013715,EnsemblFungi,498019,ASM301371v2,GCA_003013715.2,2019-09-CentersforDiseaseControlandPrevention,N,N,N,N,N,Y,fungi_ascomycota4_collection_core_61_114_1,90
4,[Candida] auris,_candida_auris_gca_003014415,EnsemblFungi,498019,Cand_auris_B11243,GCA_003014415.1,2018-03-CentersforDiseaseControlandPrevention,N,N,N,N,N,Y,fungi_ascomycota4_collection_core_61_114_1,32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1501,Zygotorulaspora mrakii str. NRRL Y-6702,zygotorulaspora_mrakii_gca_013402915,EnsemblFungi,42260,ASM1340291v1,GCA_013402915.1,2020-07-UniversityCollegeDublin,N,N,N,N,N,Y,fungi_ascomycota5_collection_core_61_114_1,227
1502,Zymoseptoria brevis str. Zb18110,zymoseptoria_brevis_gca_000966595,EnsemblFungi,1047168,ASM96659v1,GCA_000966595.1,2015-04-ChristianAlbrechtsUniversityofKiel,N,N,N,Y,N,Y,fungi_ascomycota2_collection_core_61_114_1,183
1503,Zymoseptoria tritici,zymoseptoria_tritici,EnsemblFungi,336722,MG2,GCA_000219625.1,2011-07-JGI,Y,N,Y,Y,N,Y,zymoseptoria_tritici_core_61_114_2,1
1504,Zymoseptoria tritici ST99CH_1A5,zymoseptoria_tritici_st99ch_1a5_gca_900099495,EnsemblFungi,1276529,ZT1A5 complete assembly,GCA_900099495.1,2017-08-ETH,N,N,N,N,N,Y,fungi_ascomycota4_collection_core_61_114_1,24
1505,Zymoseptoria tritici ST99CH_3D7,zymoseptoria_tritici_st99ch_3d7_gca_900091695,EnsemblFungi,1276538,Zt_ST99CH_3D7,GCA_900091695.1,2017-08-ETH,N,N,N,N,N,Y,fungi_ascomycota4_collection_core_61_114_1,2

In [8]:
df = pd.read_csv("/Users/gboldirev1/Downloads/assembly_summary_fungi_refseq.txt",sep='\t',skiprows=1)

FileNotFoundError: [Errno 2] No such file or directory: '/Users/gboldirev1/Downloads/assembly_summary_fungi_refseq.txt'

In [6]:

df['taxid'].value_counts()

taxid
4840       1
4896       1
4909       1
4950       1
4952       1
          ..
2781224    1
2819901    1
2905665    1
3039483    1
3158075    1
Name: count, Length: 659, dtype: int64

1. the only three common columns between Refseq Fungi and Ensembl Fungi are assembly_id and organism name and division (taxid). Organism name doesnt match perfectly.
2. Ensembl has another metadata list but organism name is missing so I couldn't match the species
3. I tried to download two files manually andI couldn't open the file from Ensembl because of laptop permissions

In [1]:
refseq = pd.read_csv("/Users/gboldirev1/Downloads/assembly_summary_bacteria.txt",sep='\t',skiprows=1)

KeyboardInterrupt

In [8]:
merged_df = ensembl_fungi.merge(refseq_fungi, left_on='division', right_on='taxid', how='inner')
merged_df

,#name,species,division,taxonomy_id,assembly,assembly_accession,genebuild,variation,microarray,pan_compara,...,replicon_count,scaffold_count,contig_count,annotation_provider,annotation_name,annotation_date,total_gene_count,protein_coding_gene_count,non_coding_gene_count,pubmed_id
0,_candida_auris_gca_001189475,EnsemblFungi,498019,ASM118947v1,GCA_001189475.1,2015-08-IndianInstituteofScienceIISc,N,N,N,N,...,7,7,7,Centers for Disease Control and Prevention,Annotation submitted by Centers for Disease Co...,2024-12-03,5494,5327,163,30559369
1,_candida_auris_gca_002775015,EnsemblFungi,498019,Cand_auris_B11221_V1,GCA_002775015.1,2017-11-CentersforDiseaseControlandPrevention,N,N,N,N,...,7,7,7,Centers for Disease Control and Prevention,Annotation submitted by Centers for Disease Co...,2024-12-03,5494,5327,163,30559369
2,_candida_auris_gca_003013715,EnsemblFungi,498019,ASM301371v2,GCA_003013715.2,2019-09-CentersforDiseaseControlandPrevention,N,N,N,N,...,7,7,7,Centers for Disease Control and Prevention,Annotation submitted by Centers for Disease Co...,2024-12-03,5494,5327,163,30559369
3,_candida_auris_gca_003014415,EnsemblFungi,498019,Cand_auris_B11243,GCA_003014415.1,2018-03-CentersforDiseaseControlandPrevention,N,N,N,N,...,7,7,7,Centers for Disease Control and Prevention,Annotation submitted by Centers for Disease Co...,2024-12-03,5494,5327,163,30559369
4,_candida_auris_gca_007168705,EnsemblFungi,498019,ASM716870v1,GCA_007168705.1,2019-10-LaboratoryofBacterialGenomicsPathogenG...,N,N,N,N,...,7,7,7,Centers for Disease Control and Prevention,Annotation submitted by Centers for Disease Co...,2024-12-03,5494,5327,163,30559369
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
435,zasmidium_cellare_atcc_36951_gca_010093935,EnsemblFungi,1080233,Zasce1,GCA_010093935.1,2020-02-DOEJointGenomeInstitute,N,N,N,N,...,0,267,365,DOE Joint Genome Institute,Annotation submitted by DOE Joint Genome Insti...,2020-04-27,16072,16015,50,na
436,zygosaccharomyces_rouxii_gca_000026365,EnsemblFungi,4956,ASM2636v1,GCA_000026365.1,2015-02-GenolevuresConsortium,N,N,N,Y,...,7,7,7,Genolevures Consortium,Annotation submitted by Genolevures Consortium,2024-12-04,5323,4991,332,19525356
437,zygosaccharomyces_rouxii_gca_001972345,EnsemblFungi,4956,ZYGR_assembly01,GCA_001972345.1,2017-04-YamasaCorporation,N,N,N,N,...,7,7,7,Genolevures Consortium,Annotation submitted by Genolevures Consortium,2024-12-04,5323,4991,332,19525356
438,zygotorulaspora_mrakii_gca_013402915,EnsemblFungi,42260,ASM1340291v1,GCA_013402915.1,2020-07-UniversityCollegeDublin,N,N,N,N,...,8,8,8,University College Dublin,Annotation submitted by University College Dublin,2024-12-04,5246,5038,201,na
439,zymoseptoria_tritici,EnsemblFungi,336722,MG2,GCA_000219625.1,2011-07-JGI,Y,N,Y,Y,...,21,21,24,DOE Joint Genome Institute,Annotation submitted by DOE Joint Genome Insti...,2020-02-07,10942,10941,0,21695235

In [9]:
import pandas as pd

# Ensure consistent data types
ensembl_fungi['division'] = ensembl_fungi['division'].astype(str)
refseq_fungi['taxid'] = refseq_fungi['taxid'].astype(str)

# Convert annotation_date to datetime
refseq_fungi['annotation_date'] = pd.to_datetime(refseq_fungi['annotation_date'])

# Convert genome_size to numeric if not already
refseq_fungi['genome_size'] = pd.to_numeric(refseq_fungi['genome_size'], errors='coerce')

# Step 1: For each taxid, keep the row with the latest annotation_date, and if tie, use largest genome_size
refseq_dedup = (
    refseq_fungi.sort_values(['taxid', 'annotation_date', 'genome_size'], ascending=[True, False, False])
               .drop_duplicates(subset='taxid', keep='first')
)

# Step 2: Merge
merged_df = ensembl_fungi.merge(refseq_dedup, left_on='division', right_on='taxid', how='inner')
merged_df

,#name,species,division,taxonomy_id,assembly,assembly_accession,genebuild,variation,microarray,pan_compara,...,replicon_count,scaffold_count,contig_count,annotation_provider,annotation_name,annotation_date,total_gene_count,protein_coding_gene_count,non_coding_gene_count,pubmed_id
0,_candida_auris_gca_001189475,EnsemblFungi,498019,ASM118947v1,GCA_001189475.1,2015-08-IndianInstituteofScienceIISc,N,N,N,N,...,7,7,7,Centers for Disease Control and Prevention,Annotation submitted by Centers for Disease Co...,2024-12-03,5494,5327,163,30559369
1,_candida_auris_gca_002775015,EnsemblFungi,498019,Cand_auris_B11221_V1,GCA_002775015.1,2017-11-CentersforDiseaseControlandPrevention,N,N,N,N,...,7,7,7,Centers for Disease Control and Prevention,Annotation submitted by Centers for Disease Co...,2024-12-03,5494,5327,163,30559369
2,_candida_auris_gca_003013715,EnsemblFungi,498019,ASM301371v2,GCA_003013715.2,2019-09-CentersforDiseaseControlandPrevention,N,N,N,N,...,7,7,7,Centers for Disease Control and Prevention,Annotation submitted by Centers for Disease Co...,2024-12-03,5494,5327,163,30559369
3,_candida_auris_gca_003014415,EnsemblFungi,498019,Cand_auris_B11243,GCA_003014415.1,2018-03-CentersforDiseaseControlandPrevention,N,N,N,N,...,7,7,7,Centers for Disease Control and Prevention,Annotation submitted by Centers for Disease Co...,2024-12-03,5494,5327,163,30559369
4,_candida_auris_gca_007168705,EnsemblFungi,498019,ASM716870v1,GCA_007168705.1,2019-10-LaboratoryofBacterialGenomicsPathogenG...,N,N,N,N,...,7,7,7,Centers for Disease Control and Prevention,Annotation submitted by Centers for Disease Co...,2024-12-03,5494,5327,163,30559369
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
435,zasmidium_cellare_atcc_36951_gca_010093935,EnsemblFungi,1080233,Zasce1,GCA_010093935.1,2020-02-DOEJointGenomeInstitute,N,N,N,N,...,0,267,365,DOE Joint Genome Institute,Annotation submitted by DOE Joint Genome Insti...,2020-04-27,16072,16015,50,na
436,zygosaccharomyces_rouxii_gca_000026365,EnsemblFungi,4956,ASM2636v1,GCA_000026365.1,2015-02-GenolevuresConsortium,N,N,N,Y,...,7,7,7,Genolevures Consortium,Annotation submitted by Genolevures Consortium,2024-12-04,5323,4991,332,19525356
437,zygosaccharomyces_rouxii_gca_001972345,EnsemblFungi,4956,ZYGR_assembly01,GCA_001972345.1,2017-04-YamasaCorporation,N,N,N,N,...,7,7,7,Genolevures Consortium,Annotation submitted by Genolevures Consortium,2024-12-04,5323,4991,332,19525356
438,zygotorulaspora_mrakii_gca_013402915,EnsemblFungi,42260,ASM1340291v1,GCA_013402915.1,2020-07-UniversityCollegeDublin,N,N,N,N,...,8,8,8,University College Dublin,Annotation submitted by University College Dublin,2024-12-04,5246,5038,201,na
439,zymoseptoria_tritici,EnsemblFungi,336722,MG2,GCA_000219625.1,2011-07-JGI,Y,N,Y,Y,...,21,21,24,DOE Joint Genome Institute,Annotation submitted by DOE Joint Genome Insti...,2020-02-07,10942,10941,0,21695235

In [10]:
# Convert types to ensure compatibility
ensembl_fungi['division'] = ensembl_fungi['division'].astype(str)
refseq_fungi['taxid'] = refseq_fungi['taxid'].astype(str)

# Merge without deduplication
merged_df = ensembl_fungi.merge(refseq_fungi, left_on='division', right_on='taxid', how='inner')

# Optional: sort by species and assembly identifiers
merged_df = merged_df.sort_values(['division', 'assembly_accession', '#assembly_accession'])

# Display result
merged_df

,#name,species,division,taxonomy_id,assembly,assembly_accession,genebuild,variation,microarray,pan_compara,...,replicon_count,scaffold_count,contig_count,annotation_provider,annotation_name,annotation_date,total_gene_count,protein_coding_gene_count,non_coding_gene_count,pubmed_id
236,kluyveromyces_marxianus_dmku3_1042_gca_001417885,EnsemblFungi,1003335,Kmar_1.0,GCA_001417885.1,2016-12-YamaguchiUniversity,N,N,N,N,...,8,8,8,Yamaguchi University,Annotation submitted by Yamaguchi University,2024-12-04,5151,4941,210,25834639
398,trichoderma_asperellum_gca_013423425,EnsemblFungi,101201,Tasp_IC-1_01,GCA_013423425.1,2020-07-Chubuuniversity,N,N,N,N,...,7,7,7,Academia Sinica,Annotation submitted by Academia Sinica,2024-06-26,12041,11857,184,34908505
218,fusarium_pseudograminearum,EnsemblFungi,1028729,FP7,GCA_000303195.1,2014-03-CSIRO,N,N,N,Y,...,4,279,656,CSIRO,Annotation submitted by CSIRO,2024-01-17,12445,12445,0,23028337
99,aspergillus_versicolor_cbs_583_65_gca_001890125,EnsemblFungi,1036611,Aspve1,GCA_001890125.1,2016-12-DOEJointGenomeInstitute,N,N,N,N,...,0,51,129,DOE Joint Genome Institute,Annotation submitted by DOE Joint Genome Insti...,2025-02-21,13361,13219,141,na
86,aspergillus_sydowii_cbs_593_65_gca_001890705,EnsemblFungi,1036612,Aspsy1,GCA_001890705.1,2016-12-DOEJointGenomeInstitute,N,N,N,N,...,0,97,1181,DOE Joint Genome Institute,Annotation submitted by DOE Joint Genome Insti...,2025-02-21,13716,13578,137,na
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,drechmeria_coniospora_gca_001625195,EnsemblFungi,98403,ASM162519v1,GCA_001625195.1,2016-03-BiotechnologyResearchInstituteChineseA...,N,N,N,Y,...,3,28,28,"Biotechnology Research Institute, Chinese Acad...",Annotation submitted by Biotechnology Research...,2021-04-20,8445,8236,141,26975455
230,hyphopichia_burtonii_nrrl_y_1933_gca_001661395,EnsemblFungi,984485,Hypbu1,GCA_001661395.1,2016-09-DOEJointGenomeInstitute,N,N,N,Y,...,0,27,243,NCBI RefSeq,Annotation submitted by NCBI RefSeq,2017-02-15,6166,5995,171,27535936
106,babjeviella_inositovora_nrrl_y_12698_gca_00166...,EnsemblFungi,984486,Babin1,GCA_001661335.1,2016-09-DOEJointGenomeInstitute,N,N,N,Y,...,0,49,211,DOE Joint Genome Institute,Annotation submitted by DOE Joint Genome Insti...,2020-02-03,6795,6397,393,27535936
378,suhomyces_tanzawaensis_nrrl_y_17324_gca_001661415,EnsemblFungi,984487,Canta1,GCA_001661415.1,2016-09-DOEJointGenomeInstitute,N,N,N,Y,...,0,16,249,DOE Joint Genome Institute,Annotation submitted by DOE Joint Genome Insti...,2019-11-29,6143,5884,257,27535936
419,vittaforma_corneae_atcc_50505_gca_000231115,EnsemblFungi,993615,Vitt_corn_V1,GCA_000231115.1,2012-12-BroadInstitute,N,N,N,Y,...,0,220,314,Broad Institute,Annotation submitted by Broad Institute,2024-01-02,2293,2239,54,na

In [11]:
#for 3 and 4 assemblies make 12 blast runs and pick the highest score

In [11]:
merged_df[['#assembly_accession','assembly_accession','assembly','ftp_path','organism_name','taxid']]

,#assembly_accession,assembly_accession,assembly,ftp_path,organism_name,taxid
236,GCF_001417885.1,2016-12-YamaguchiUniversity,GCA_001417885.1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,Kluyveromyces marxianus DMKU3-1042,1003335
398,GCF_020647865.1,2020-07-Chubuuniversity,GCA_013423425.1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,Trichoderma asperellum,101201
218,GCF_000303195.2,2014-03-CSIRO,GCA_000303195.1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,Fusarium pseudograminearum CS3096,1028729
99,GCF_001890125.1,2016-12-DOEJointGenomeInstitute,GCA_001890125.1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,Aspergillus versicolor CBS 583.65,1036611
86,GCF_001890705.1,2016-12-DOEJointGenomeInstitute,GCA_001890705.1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,Aspergillus sydowii CBS 593.65,1036612
...,...,...,...,...,...,...
182,GCF_001625195.1,2016-03-BiotechnologyResearchInstituteChineseA...,GCA_001625195.1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,Drechmeria coniospora,98403
230,GCF_001661395.1,2016-09-DOEJointGenomeInstitute,GCA_001661395.1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,Hyphopichia burtonii NRRL Y-1933,984485
106,GCF_001661335.1,2016-09-DOEJointGenomeInstitute,GCA_001661335.1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,Babjeviella inositovora NRRL Y-12698,984486
378,GCF_001661415.1,2016-09-DOEJointGenomeInstitute,GCA_001661415.1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,Suhomyces tanzawaensis NRRL Y-17324,984487
419,GCF_000231115.1,2012-12-BroadInstitute,GCA_000231115.1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,Vittaforma corneae ATCC 50505,993615

In [12]:
import pandas as pd

# Increase column width so full strings are shown
pd.set_option('display.max_colwidth', None)

# Display your DataFrame
print(merged_df)

                                                  #name       species  \
236    kluyveromyces_marxianus_dmku3_1042_gca_001417885  EnsemblFungi
398                trichoderma_asperellum_gca_013423425  EnsemblFungi
218                          fusarium_pseudograminearum  EnsemblFungi
99      aspergillus_versicolor_cbs_583_65_gca_001890125  EnsemblFungi
86         aspergillus_sydowii_cbs_593_65_gca_001890705  EnsemblFungi
..                                                  ...           ...
182                 drechmeria_coniospora_gca_001625195  EnsemblFungi
230      hyphopichia_burtonii_nrrl_y_1933_gca_001661395  EnsemblFungi
106  babjeviella_inositovora_nrrl_y_12698_gca_001661335  EnsemblFungi
378   suhomyces_tanzawaensis_nrrl_y_17324_gca_001661415  EnsemblFungi
419         vittaforma_corneae_atcc_50505_gca_000231115  EnsemblFungi

    division   taxonomy_id         assembly  \
236  1003335      Kmar_1.0  GCA_001417885.1
398   101201  Tasp_IC-1_01  GCA_013423425.1
218  1028729           FP7  GCA_000303195.1
99   1036611        Aspve1  GCA_001890125.1
86   1036612        Aspsy1  GCA_001890705.1
..       ...           ...              ...
182    98403   ASM162519v1  GCA_001625195.1
230   984485        Hypbu1  GCA_001661395.1
106   984486        Babin1  GCA_001661335.1
378   984487        Canta1  GCA_001661415.1
419   993615  Vitt_corn_V1  GCA_000231115.1

                                                             assembly_accession  \
236                                                 2016-12-YamaguchiUniversity
398                                                     2020-07-Chubuuniversity
218                                                               2014-03-CSIRO
99                                              2016-12-DOEJointGenomeInstitute
86                                              2016-12-DOEJointGenomeInstitute
..                                                                          ...
182  2016-03-BiotechnologyResearchInstituteChineseAcademyofAgriculturalSciences
230                                             2016-09-DOEJointGenomeInstitute
106                                             2016-09-DOEJointGenomeInstitute
378                                             2016-09-DOEJointGenomeInstitute
419                                                      2012-12-BroadInstitute

    genebuild variation microarray pan_compara  ... replicon_count  \
236         N         N          N           N  ...              8
398         N         N          N           N  ...              7
218         N         N          N           Y  ...              4
99          N         N          N           N  ...              0
86          N         N          N           N  ...              0
..        ...       ...        ...         ...  ...            ...
182         N         N          N           Y  ...              3
230         N         N          N           Y  ...              0
106         N         N          N           Y  ...              0
378         N         N          N           Y  ...              0
419         N         N          N           Y  ...              0

    scaffold_count contig_count  \
236              8            8
398              7            7
218            279          656
99              51          129
86              97         1181
..             ...          ...
182             28           28
230             27          243
106             49          211
378             16          249
419            220          314

                                                            annotation_provider  \
236                                                        Yamaguchi University
398                                                             Academia Sinica
218                                                                       CSIRO
99                                                   DOE Joint Genome Institute
86                                                   DOE Joint Genome Institute
..                                                                          ...
182  Biotechnology Research Institute, Chinese Academy of Agricultural Sciences
230                                                                 NCBI RefSeq
106                                                  DOE Joint Genome Institute
378                                                  DOE Joint Genome Institute
419                                                             Broad Institute

                                                                                        annotation_name  \
236                                                        Annotation submitted by Yamaguchi University
398                                                             Annotation submitted by Academia Sinica
218                                                                       Annotation submitted by CSIRO
99                                                   Annotation submitted by DOE Joint Genome Institute
86                                                   Annotation submitted by DOE Joint Genome Institute
..                                                                                                  ...
182  Annotation submitted by Biotechnology Research Institute, Chinese Academy of Agricultural Sciences
230                                                                 Annotation submitted by NCBI RefSeq
106                                                  Annotation submitted by DOE Joint Genome Institute
378                                                  Annotation submitted by DOE Joint Genome Institute
419                                                             Annotation submitted by Broad Institute

    annotation_date total_gene_count protein_coding_gene_count  \
236      2024-12-04             5151                      4941
398      2024-06-26            12041                     11857
218      2024-01-17            12445                     12445
99       2025-02-21            13361                     13219
86       2025-02-21            13716                     13578
..              ...              ...                       ...
182      2021-04-20             8445                      8236
230      2017-02-15             6166                      5995
106      2020-02-03             6795                      6397
378      2019-11-29             6143                      5884
419      2024-01-02             2293                      2239

    non_coding_gene_count pubmed_id
236                   210  25834639
398                   184  34908505
218                     0  23028337
99                    141        na
86                    137        na
..                    ...       ...
182                   141  26975455
230                   171  27535936
106                   393  27535936
378                   257  27535936
419                    54        na

[440 rows x 53 columns]

In [18]:
import pandas as pd
from ftplib import FTP
import os
import gzip
import shutil

# Load accessions
df = merged_df.copy()
os.makedirs("downloads", exist_ok=True)

# Convert GCA_001417885.1 → 001417885 and GCA_001417885.1 → GCA001417885v1
def numeric_accession(acc):
    return acc.split('_')[1].split('.')[0]

def formatted_accession(acc):
    base = numeric_accession(acc)
    version = acc.split('.')[-1]
    return f"GCA{base}v{version}"

ftp_host = "ftp.ensemblgenomes.ebi.ac.uk"
base_dir = "/pub/fungi/current/fasta"
numeric_map = {numeric_accession(a): a for a in df['assembly']}
formatted_map = {formatted_accession(a): a for a in df['assembly']}
fasta_map = {}

with FTP(ftp_host) as ftp:
    ftp.login()
    ftp.cwd(base_dir)
    top_level_dirs = ftp.nlst()

    for top_dir in top_level_dirs:
        full_top_path = f"{base_dir}/{top_dir}"

        if top_dir.startswith("fungi_"):
            # Dive into nested folders inside fungi_*
            try:
                ftp.cwd(full_top_path)
                inner_dirs = ftp.nlst()

                for inner_dir in inner_dirs:
                    dna_path = f"{full_top_path}/{inner_dir}/dna"
                    try:
                        ftp.cwd(dna_path)
                        files = ftp.nlst()

                        # Only check .dna.toplevel.fa.gz
                        for file in files:
                            if not file.endswith(".dna.toplevel.fa.gz"):
                                continue

                            for num_id, original_acc in numeric_map.items():
                                if num_id in file:
                                    gz_path = f"downloads/{file}"
                                    fasta_path = gz_path[:-3]

                                    if not os.path.exists(fasta_path):
                                        print(f"Downloading {file} from {dna_path}...")
                                        with open(gz_path, "wb") as out_file:
                                            ftp.retrbinary(f"RETR {file}", out_file.write)
                                        with gzip.open(gz_path, 'rb') as f_in, open(fasta_path, 'wb') as f_out:
                                            shutil.copyfileobj(f_in, f_out)

                                    fasta_map[original_acc] = os.path.basename(fasta_path)
                                    break  # Stop after one match
                        ftp.cwd(full_top_path)
                    except Exception as e:
                        print(f"Skipping {dna_path}: {e}")
            except Exception as e:
                print(f"Skipping {full_top_path}: {e}")
        else:
            # Normal folder: search in /dna for file with full formatted accession (GCAxxxxxxvY)
            dna_path = f"{full_top_path}/dna"
            try:
                ftp.cwd(dna_path)
                files = ftp.nlst()

                for file in files:
                    if not file.endswith(".dna.toplevel.fa.gz"):
                        continue

                    for full_id, original_acc in formatted_map.items():
                        if full_id in file:
                            gz_path = f"downloads/{file}"
                            fasta_path = gz_path[:-3]

                            if not os.path.exists(fasta_path):
                                print(f"Downloading {file} from {dna_path}...")
                                with open(gz_path, "wb") as out_file:
                                    ftp.retrbinary(f"RETR {file}", out_file.write)
                                with gzip.open(gz_path, 'rb') as f_in, open(fasta_path, 'wb') as f_out:
                                    shutil.copyfileobj(f_in, f_out)

                            fasta_map[original_acc] = os.path.basename(fasta_path)
                            break
                ftp.cwd(base_dir)
            except Exception as e:
                print(f"Skipping {dna_path}: {e}")

# Add column and save
df['fasta_filename'] = df['assembly'].map(fasta_map)
df.to_csv("accessions_with_fasta.csv", index=False)
print("\n✅ Done! Output saved to 'accessions_with_fasta.csv'")

Downloading Aspergillus_fischeri.GCA000149645v4.dna.toplevel.fa.gz from /pub/fungi/current/fasta/aspergillus_fischeri/dna...
Downloading Aspergillus_fumigatus.GCA000002655v1.dna.toplevel.fa.gz from /pub/fungi/current/fasta/aspergillus_fumigatus/dna...
Downloading Aspergillus_lentulus.GCA001445615v2.dna.toplevel.fa.gz from /pub/fungi/current/fasta/aspergillus_lentulus/dna...
Downloading Candida_albicans.GCA000182965v3.dna.toplevel.fa.gz from /pub/fungi/current/fasta/candida_albicans/dna...
Downloading Candida_auris.GCA002759435v2.dna.toplevel.fa.gz from /pub/fungi/current/fasta/candida_auris/dna...
Downloading Candida_duobushaemulonis.GCA002926085v1.dna.toplevel.fa.gz from /pub/fungi/current/fasta/candida_duobushaemulonis/dna...
Downloading Candida_haemuloni.GCA002926055v1.dna.toplevel.fa.gz from /pub/fungi/current/fasta/candida_haemuloni/dna...
Downloading Candida_pseudohaemulonis.GCA003013735v1.dna.toplevel.fa.gz from /pub/fungi/current/fasta/candida_pseudohaemulonis/dna...
Downloading Candida_tropicalis.GCA000006335v3.dna.toplevel.fa.gz from /pub/fungi/current/fasta/candida_tropicalis/dna...
Downloading Arthrobotrys_oligospora_atcc_24927_gca_000225545.AOL24927_1.0.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/arthrobotrys_oligospora_atcc_24927_gca_000225545/dna...
Downloading Aspergillus_ruber_cbs_135680_gca_000600275.Eurhe1.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/aspergillus_ruber_cbs_135680_gca_000600275/dna...
Downloading Aureobasidium_melanogenum_cbs_110374_gca_000721775.Aureobasidium_pullulans_var._melanogenum_CBS_110374_v1.0.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/aureobasidium_melanogenum_cbs_110374_gca_000721775/dna...
Downloading Aureobasidium_namibiae_cbs_147_97_gca_000721765.Aureobasidium_pullulans_var._namibiae_CBS_147.97_v1.0.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/aureobasidium_namibiae_cbs_147_97_gca_000721765/dna...
Downloading Aureobasidium_pullulans_exf_150_gca_000721785.Aureobasidium_pullulans_var._pullulans_EXF-150_assembly_version_1.0.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/aureobasidium_pullulans_exf_150_gca_000721785/dna...
Downloading Aureobasidium_subglaciale_exf_2481_gca_000721755.Aureobasidium_pullulans_var._subglaciale_EXF-2481_v1.0.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/aureobasidium_subglaciale_exf_2481_gca_000721755/dna...
Downloading Baudoinia_panamericana_uamh_10762_gca_000338955.Bauco1.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/baudoinia_panamericana_uamh_10762_gca_000338955/dna...
Downloading Beauveria_bassiana_arsef_2860_gca_000280675.ASM28067v1.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/beauveria_bassiana_arsef_2860_gca_000280675/dna...
Downloading Bipolaris_oryzae_atcc_44560_gca_000523455.Cochliobolus_miyabeanus_v1.0.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/bipolaris_oryzae_atcc_44560_gca_000523455/dna...
Downloading Bipolaris_sorokiniana_nd90pr_gca_000338995.Cocsa1.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/bipolaris_sorokiniana_nd90pr_gca_000338995/dna...
Downloading Bipolaris_zeicola_26_r_13_gca_000523435.Cochliobolus_carbonum_v1.0.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/bipolaris_zeicola_26_r_13_gca_000523435/dna...
Downloading Blastomyces_dermatitidis_er_3_gca_000003525.BD_ER3_V1.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/blastomyces_dermatitidis_er_3_gca_000003525/dna...
Downloading Blastomyces_gilchristii_slh14081_gca_000003855.BD_SLH14081_V1.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/blastomyces_gilchristii_slh14081_gca_000003855/dna...
Downloading Candida_dubliniensis_cd36_gca_000026945.ASM2694v1.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/candida_dubliniensis_cd36_gca_000026945/dna...
Downloading Candida_orthopsilosis_co_90_125_gca_000315875.ASM31587v1.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/candida_orthopsilosis_co_90_125_gca_000315875/dna...
Downloading Capronia_coronata_cbs_617_96_gca_000585585.Capr_coro_CBS_617_96_V1.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/capronia_coronata_cbs_617_96_gca_000585585/dna...
Downloading Capronia_epimyces_cbs_606_96_gca_000585565.Capr_epim_CBS_606_96_V1.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/capronia_epimyces_cbs_606_96_gca_000585565/dna...
Downloading Chaetomium_globosum_cbs_148_51_gca_000143365.ASM14336v1.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/chaetomium_globosum_cbs_148_51_gca_000143365/dna...
Downloading Chaetomium_thermophilum_var_thermophilum_dsm_1495_gca_000221225.CTHT_3.0.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/chaetomium_thermophilum_var_thermophilum_dsm_1495_gca_000221225/dna...
Downloading Cladophialophora_carrionii_cbs_160_54_gca_000365165.Clad_carr_CBS_160_54_V1.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/cladophialophora_carrionii_cbs_160_54_gca_000365165/dna...
Downloading Cladophialophora_psammophila_cbs_110553_gca_000585535.Clad_psam_CBS_110553_V1.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/cladophialophora_psammophila_cbs_110553_gca_000585535/dna...
Downloading Cladophialophora_yegresii_cbs_114405_gca_000585515.Clad_yegr_CBS_114405_V1.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/cladophialophora_yegresii_cbs_114405_gca_000585515/dna...
Downloading Coccidioides_immitis_rs_gca_000149335.ASM14933v2.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/coccidioides_immitis_rs_gca_000149335/dna...
Downloading Coccidioides_posadasii_str_silveira_gca_000170175.CPS2.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/coccidioides_posadasii_str_silveira_gca_000170175/dna...
Downloading Coniosporium_apollinis_cbs_100218_gca_000281105.Coni_apol_CBS100218__V1.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/coniosporium_apollinis_cbs_100218_gca_000281105/dna...
Downloading Cordyceps_militaris_cm01_gca_000225605.CmilitarisCM01_v01.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/cordyceps_militaris_cm01_gca_000225605/dna...
Downloading Cyphellophora_europaea_cbs_101466_gca_000365145.Phia_euro_CBS_101466_V1.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/cyphellophora_europaea_cbs_101466_gca_000365145/dna...
Downloading Debaryomyces_hansenii_cbs767_gca_000006445.ASM644v2.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/debaryomyces_hansenii_cbs767_gca_000006445/dna...
Downloading Endocarpon_pusillum_z07020_gca_000464535.EPUS.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/endocarpon_pusillum_z07020_gca_000464535/dna...
Downloading Eremothecium_cymbalariae_dbvpg_7215_gca_000235365.ASM23536v1.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/eremothecium_cymbalariae_dbvpg_7215_gca_000235365/dna...
Downloading Exophiala_aquamarina_cbs_119918_gca_000709125.Exop_aqua_CBS_119918_V1.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/exophiala_aquamarina_cbs_119918_gca_000709125/dna...
Downloading Exophiala_dermatitidis_nih_ut8656_gca_000230625.Exop_derm_V1.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/exophiala_dermatitidis_nih_ut8656_gca_000230625/dna...
Downloading Exserohilum_turcica_et28a_gca_000359705.Setospaeria_trucica_Et28A_v1.0.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/exserohilum_turcica_et28a_gca_000359705/dna...
Downloading Fusarium_odoratissimum_nrrl_54006_gca_000260195.FO_II5_V1.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/fusarium_odoratissimum_nrrl_54006_gca_000260195/dna...
Downloading Fusarium_oxysporum_fo47_gca_000271705.FO_Fo47_V1.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/fusarium_oxysporum_fo47_gca_000271705/dna...
Downloading Glarea_lozoyensis_atcc_20868_gca_000409485.GLAREA.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/glarea_lozoyensis_atcc_20868_gca_000409485/dna...
Downloading Grosmannia_clavigera_kw1407_gca_000143105.Sanger-454-IlluminaPA_2.0.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/grosmannia_clavigera_kw1407_gca_000143105/dna...
Downloading Histoplasma_capsulatum_g186ar_gca_000150115.ASM15011v1.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/histoplasma_capsulatum_g186ar_gca_000150115/dna...
Downloading Histoplasma_capsulatum_nam1_gca_000149585.ASM14958v1.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/histoplasma_capsulatum_nam1_gca_000149585/dna...
Downloading Kazachstania_africana_cbs_2517_gca_000304475.Ka_CBS2517.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/kazachstania_africana_cbs_2517_gca_000304475/dna...
Downloading Kazachstania_naganishii_cbs_8797_gca_000348985.ASM34898v1.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/kazachstania_naganishii_cbs_8797_gca_000348985/dna...
Downloading Kluyveromyces_lactis_gca_000002515.ASM251v1.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/kluyveromyces_lactis_gca_000002515/dna...
Downloading Kuraishia_capsulata_cbs_1993_gca_000576695.AUH_PRJEB4427_v1.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/kuraishia_capsulata_cbs_1993_gca_000576695/dna...
Downloading Lachancea_thermotolerans_cbs_6340_gca_000142805.ASM14280v1.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/lachancea_thermotolerans_cbs_6340_gca_000142805/dna...
Downloading Metarhizium_anisopliae_arsef_23_gca_000187425.MAA_2.0.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/metarhizium_anisopliae_arsef_23_gca_000187425/dna...
Downloading Meyerozyma_guilliermondii_atcc_6260_gca_000149425.ASM14942v1.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/meyerozyma_guilliermondii_atcc_6260_gca_000149425/dna...
Downloading Microsporum_canis_cbs_113480_gca_000151145.ASM15114v1.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/microsporum_canis_cbs_113480_gca_000151145/dna...
Downloading Nannizzia_gypsea_cbs_118893_gca_000150975.MS_CBS118893.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/nannizzia_gypsea_cbs_118893_gca_000150975/dna...
Downloading Naumovozyma_castellii_cbs_4309_gca_000237345.ASM23734v1.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/naumovozyma_castellii_cbs_4309_gca_000237345/dna...
Downloading Naumovozyma_dairenensis_cbs_421_gca_000227115.ASM22711v2.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/naumovozyma_dairenensis_cbs_421_gca_000227115/dna...
Downloading Neurospora_tetrasperma_fgsc_2508_gca_000213175.v2.0.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/neurospora_tetrasperma_fgsc_2508_gca_000213175/dna...
Downloading Ogataea_parapolymorpha_dl_1_gca_000187245.Hansenula_2.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/ogataea_parapolymorpha_dl_1_gca_000187245/dna...
Downloading Paracoccidioides_brasiliensis_pb18_gca_000150735.Paracocci_br_Pb18_V2.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/paracoccidioides_brasiliensis_pb18_gca_000150735/dna...
Downloading Paracoccidioides_sp_lutzii_pb01_gca_000150705.Paracocci_br_Pb01_V2.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/paracoccidioides_sp_lutzii_pb01_gca_000150705/dna...
Downloading Penicillium_expansum_gca_000769735.ASM76973v1.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/penicillium_expansum_gca_000769735/dna...
Downloading Penicillium_expansum_gca_000769755.PEX1.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/penicillium_expansum_gca_000769755/dna...
Downloading Pestalotiopsis_fici_w106_1_gca_000516985.PFICI.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/pestalotiopsis_fici_w106_1_gca_000516985/dna...
Downloading Phaeoacremonium_minimum_ucrpa7_gca_000392275.UCRPA7V03.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/phaeoacremonium_minimum_ucrpa7_gca_000392275/dna...
Downloading Pichia_kudriavzevii_gca_000764455.ASM76445v1.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/pichia_kudriavzevii_gca_000764455/dna...
Downloading Pneumocystis_murina_b123_gca_000349005.Pneumo_murina_B123_V4.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/pneumocystis_murina_b123_gca_000349005/dna...
Downloading Podospora_anserina_s_mat_gca_000226545.ASM22654v1.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/podospora_anserina_s_mat_gca_000226545/dna...
Downloading Pseudocercospora_fijiensis_cirad86_gca_000340215.Mycfi2.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/pseudocercospora_fijiensis_cirad86_gca_000340215/dna...
Downloading Saccharomyces_kudriavzevii_ifo_1802_gca_000167075.Saccharomyces_kudriavzevii_strain_IFO1802_v1.0.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/saccharomyces_kudriavzevii_ifo_1802_gca_000167075/dna...
Downloading Scedosporium_apiospermum_gca_000732125.ScApio1.0.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/scedosporium_apiospermum_gca_000732125/dna...
Downloading Scheffersomyces_stipitis_cbs_6054_gca_000209165.ASM20916v1.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/scheffersomyces_stipitis_cbs_6054_gca_000209165/dna...
Downloading Spathaspora_passalidarum_nrrl_y_27907_gca_000223485.Spathaspora_passalidarum_v2.0.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/spathaspora_passalidarum_nrrl_y_27907_gca_000223485/dna...
Downloading Sphaerulina_musiva_so2202_gca_000320565.Septoria_musiva_SO2202_v1.0.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/sphaerulina_musiva_so2202_gca_000320565/dna...
Downloading Talaromyces_stipitatus_atcc_10500_gca_000003125.JCVI-TSTA1-3.0.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/talaromyces_stipitatus_atcc_10500_gca_000003125/dna...
Downloading Tetrapisispora_blattae_cbs_6284_gca_000315915.ASM31591v1.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/tetrapisispora_blattae_cbs_6284_gca_000315915/dna...
Downloading Tetrapisispora_phaffii_cbs_4417_gca_000236905.ASM23690v1.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/tetrapisispora_phaffii_cbs_4417_gca_000236905/dna...
Downloading Thermothelomyces_thermophilus_atcc_42464_gca_000226095.ASM22609v1.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/thermothelomyces_thermophilus_atcc_42464_gca_000226095/dna...
Downloading Thermothielavioides_terrestris_nrrl_8126_gca_000226115.ASM22611v1.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/thermothielavioides_terrestris_nrrl_8126_gca_000226115/dna...
Downloading Torulaspora_delbrueckii_gca_000243375.ASM24337v1.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/torulaspora_delbrueckii_gca_000243375/dna...
Downloading Trichophyton_benhamiae_cbs_112371_gca_000151125.ASM15112v2.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/trichophyton_benhamiae_cbs_112371_gca_000151125/dna...
Downloading Trichophyton_rubrum_cbs_118892_gca_000151425.ASM15142v1.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/trichophyton_rubrum_cbs_118892_gca_000151425/dna...
Downloading Trichophyton_verrucosum_hki_0517_gca_000151505.ASM15150v1.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/trichophyton_verrucosum_hki_0517_gca_000151505/dna...
Downloading Uncinocarpus_reesii_1704_gca_000003515.ASM351v2.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/uncinocarpus_reesii_1704_gca_000003515/dna...
Downloading Ustilaginoidea_virens_gca_000687475.Assembly_for_version_1_of_the_Villosiclava_virens_genome.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/ustilaginoidea_virens_gca_000687475/dna...
Downloading Vanderwaltozyma_polyspora_dsm_70294_gca_000150035.ASM15003v1.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/vanderwaltozyma_polyspora_dsm_70294_gca_000150035/dna...
Downloading Verticillium_alfalfae_vams_102_gca_000150825.ASM15082v1.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/verticillium_alfalfae_vams_102_gca_000150825/dna...
Downloading Wickerhamomyces_ciferrii_gca_000313485.ASM31348v1.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/wickerhamomyces_ciferrii_gca_000313485/dna...
Downloading Zygosaccharomyces_rouxii_gca_000026365.ASM2636v1.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota1_collection/zygosaccharomyces_rouxii_gca_000026365/dna...
Downloading Aspergillus_nidulans_fgsc_a4_gca_000149205.ASM14920v2.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota2_collection/aspergillus_nidulans_fgsc_a4_gca_000149205/dna...
Downloading Candida_albicans_sc5314_gca_000784635.Cand_albi_SC5314_V4.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota2_collection/candida_albicans_sc5314_gca_000784635/dna...
Downloading Candida_albicans_sc5314_gca_000784655.Cand_albi_SC5314_V3.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota2_collection/candida_albicans_sc5314_gca_000784655/dna...
Downloading Cladophialophora_bantiana_cbs_173_52_gca_000835475.Clad_bant_CBS_173_52_V1.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota2_collection/cladophialophora_bantiana_cbs_173_52_gca_000835475/dna...
Downloading Cladophialophora_immunda_gca_000835495.Clad_immu_CBS83496_V1.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota2_collection/cladophialophora_immunda_gca_000835495/dna...
Downloading Diplodia_seriata_gca_001006355.UCDDS831v0.1.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota2_collection/diplodia_seriata_gca_001006355/dna...
Downloading Exophiala_mesophila_gca_000836275.Exop_meso_CBS40295_V1.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota2_collection/exophiala_mesophila_gca_000836275/dna...
Downloading Exophiala_oligosperma_gca_000835515.Exop_olig_CBS72588_V1.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota2_collection/exophiala_oligosperma_gca_000835515/dna...
Downloading Exophiala_spinifera_gca_000836115.Exop_spin_CBS89968_V1.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota2_collection/exophiala_spinifera_gca_000836115/dna...
Downloading Exophiala_xenobiotica_gca_000835505.Exop_xeno_CBS118157_V1.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota2_collection/exophiala_xenobiotica_gca_000835505/dna...
Downloading Fonsecaea_multimorphosa_cbs_102226_gca_000836435.Fons_mult_CBS_102226_V1.dna.toplevel.fa.gz from /pub/fungi/current/fasta/fungi_ascomycota2_collection/fonsecaea_multimorphosa_cbs_102226_gca_000836435/dna...

In [13]:
genomes = pd.read_csv("accessions_with_fasta.csv")
genomes

,#name,species,division,taxonomy_id,assembly,assembly_accession,genebuild,variation,microarray,pan_compara,...,contig_count,annotation_provider,annotation_name,annotation_date,total_gene_count,protein_coding_gene_count,non_coding_gene_count,pubmed_id,fasta_filename,downloaded_filename
0,kluyveromyces_marxianus_dmku3_1042_gca_001417885,EnsemblFungi,1003335,Kmar_1.0,GCA_001417885.1,2016-12-YamaguchiUniversity,N,N,N,N,...,8,Yamaguchi University,Annotation submitted by Yamaguchi University,2024-12-04,5151,4941,210,25834639,Kluyveromyces_marxianus_dmku3_1042_gca_001417885.Kmar_1.0.dna.toplevel.fa,GCF_001417885.1_Kmar_1.0_genomic.fna.gz
1,trichoderma_asperellum_gca_013423425,EnsemblFungi,101201,Tasp_IC-1_01,GCA_013423425.1,2020-07-Chubuuniversity,N,N,N,N,...,7,Academia Sinica,Annotation submitted by Academia Sinica,2024-06-26,12041,11857,184,34908505,Trichoderma_asperellum_gca_013423425.Tasp_IC-1_01.dna.toplevel.fa,GCF_020647865.1_ASM2064786v1_genomic.fna.gz
2,fusarium_pseudograminearum,EnsemblFungi,1028729,FP7,GCA_000303195.1,2014-03-CSIRO,N,N,N,Y,...,656,CSIRO,Annotation submitted by CSIRO,2024-01-17,12445,12445,0,23028337,NaN,GCF_000303195.2_FP7_genomic.fna.gz
3,aspergillus_versicolor_cbs_583_65_gca_001890125,EnsemblFungi,1036611,Aspve1,GCA_001890125.1,2016-12-DOEJointGenomeInstitute,N,N,N,N,...,129,DOE Joint Genome Institute,Annotation submitted by DOE Joint Genome Institute,2025-02-21,13361,13219,141,na,Aspergillus_versicolor_cbs_583_65_gca_001890125.Aspve1.dna.toplevel.fa,GCF_001890125.1_Aspve1_genomic.fna.gz
4,aspergillus_sydowii_cbs_593_65_gca_001890705,EnsemblFungi,1036612,Aspsy1,GCA_001890705.1,2016-12-DOEJointGenomeInstitute,N,N,N,N,...,1181,DOE Joint Genome Institute,Annotation submitted by DOE Joint Genome Institute,2025-02-21,13716,13578,137,na,Aspergillus_sydowii_cbs_593_65_gca_001890705.Aspsy1.dna.toplevel.fa,GCF_001890705.1_Aspsy1_genomic.fna.gz
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
435,drechmeria_coniospora_gca_001625195,EnsemblFungi,98403,ASM162519v1,GCA_001625195.1,2016-03-BiotechnologyResearchInstituteChineseAcademyofAgriculturalSciences,N,N,N,Y,...,28,"Biotechnology Research Institute, Chinese Academy of Agricultural Sciences","Annotation submitted by Biotechnology Research Institute, Chinese Academy of Agricultural Sciences",2021-04-20,8445,8236,141,26975455,Drechmeria_coniospora_gca_001625195.ASM162519v1.dna.toplevel.fa,identical_genomic.fna.gz
436,hyphopichia_burtonii_nrrl_y_1933_gca_001661395,EnsemblFungi,984485,Hypbu1,GCA_001661395.1,2016-09-DOEJointGenomeInstitute,N,N,N,Y,...,243,NCBI RefSeq,Annotation submitted by NCBI RefSeq,2017-02-15,6166,5995,171,27535936,Hyphopichia_burtonii_nrrl_y_1933_gca_001661395.Hypbu1.dna.toplevel.fa,GCF_001661395.1_Hypbu1_genomic.fna.gz
437,babjeviella_inositovora_nrrl_y_12698_gca_001661335,EnsemblFungi,984486,Babin1,GCA_001661335.1,2016-09-DOEJointGenomeInstitute,N,N,N,Y,...,211,DOE Joint Genome Institute,Annotation submitted by DOE Joint Genome Institute,2020-02-03,6795,6397,393,27535936,Babjeviella_inositovora_nrrl_y_12698_gca_001661335.Babin1.dna.toplevel.fa,GCF_001661335.1_Babin1_genomic.fna.gz
438,suhomyces_tanzawaensis_nrrl_y_17324_gca_001661415,EnsemblFungi,984487,Canta1,GCA_001661415.1,2016-09-DOEJointGenomeInstitute,N,N,N,Y,...,249,DOE Joint Genome Institute,Annotation submitted by DOE Joint Genome Institute,2019-11-29,6143,5884,257,27535936,Suhomyces_tanzawaensis_nrrl_y_17324_gca_001661415.Canta1.dna.toplevel.fa,GCF_001661415.1_Canta1_genomic.fna.gz
439,vittaforma_corneae_atcc_50505_gca_000231115,EnsemblFungi,993615,Vitt_corn_V1,GCA_000231115.1,2012-12-BroadInstitute,N,N,N,Y,...,314,Broad Institute,Annotation submitted by Broad Institute,2024-01-02,2293,2239,54,na,Vittaforma_corneae_atcc_50505_gca_000231115.Vitt_corn_V1.dna.toplevel.fa,GCF_000231115.1_Vitt_corn_V1_genomic.fna.gz

In [21]:
filtered_df = genomes[
    genomes['downloaded_filename'].notna() & (genomes['downloaded_filename'].str.strip() != '') &
    genomes['fasta_filename'].notna() & (genomes['fasta_filename'].str.strip() != '')
].copy()

# Reset index if needed
filtered_df.reset_index(drop=True, inplace=True)
filtered_df

,#name,species,division,taxonomy_id,assembly,assembly_accession,genebuild,variation,microarray,pan_compara,...,contig_count,annotation_provider,annotation_name,annotation_date,total_gene_count,protein_coding_gene_count,non_coding_gene_count,pubmed_id,fasta_filename,downloaded_filename
0,kluyveromyces_marxianus_dmku3_1042_gca_001417885,EnsemblFungi,1003335,Kmar_1.0,GCA_001417885.1,2016-12-YamaguchiUniversity,N,N,N,N,...,8,Yamaguchi University,Annotation submitted by Yamaguchi University,2024-12-04,5151,4941,210,25834639,Kluyveromyces_marxianus_dmku3_1042_gca_001417885.Kmar_1.0.dna.toplevel.fa,GCF_001417885.1_Kmar_1.0_genomic.fna.gz
1,trichoderma_asperellum_gca_013423425,EnsemblFungi,101201,Tasp_IC-1_01,GCA_013423425.1,2020-07-Chubuuniversity,N,N,N,N,...,7,Academia Sinica,Annotation submitted by Academia Sinica,2024-06-26,12041,11857,184,34908505,Trichoderma_asperellum_gca_013423425.Tasp_IC-1_01.dna.toplevel.fa,GCF_020647865.1_ASM2064786v1_genomic.fna.gz
2,aspergillus_versicolor_cbs_583_65_gca_001890125,EnsemblFungi,1036611,Aspve1,GCA_001890125.1,2016-12-DOEJointGenomeInstitute,N,N,N,N,...,129,DOE Joint Genome Institute,Annotation submitted by DOE Joint Genome Institute,2025-02-21,13361,13219,141,na,Aspergillus_versicolor_cbs_583_65_gca_001890125.Aspve1.dna.toplevel.fa,GCF_001890125.1_Aspve1_genomic.fna.gz
3,aspergillus_sydowii_cbs_593_65_gca_001890705,EnsemblFungi,1036612,Aspsy1,GCA_001890705.1,2016-12-DOEJointGenomeInstitute,N,N,N,N,...,1181,DOE Joint Genome Institute,Annotation submitted by DOE Joint Genome Institute,2025-02-21,13716,13578,137,na,Aspergillus_sydowii_cbs_593_65_gca_001890705.Aspsy1.dna.toplevel.fa,GCF_001890705.1_Aspsy1_genomic.fna.gz
4,tilletiaria_anomala_ubc_951_gca_000711695,EnsemblFungi,1037660,Tilletiaria anomala UBC 951 v1.0,GCA_000711695.1,2014-05-DOEJointGenomeInstitute,N,N,N,Y,...,289,NCBI RefSeq,Annotation submitted by NCBI RefSeq,2015-08-12,6869,6805,63,24926052,Tilletiaria_anomala_ubc_951_gca_000711695.Tilletiaria_anomala_UBC_951_v1.0.dna.toplevel.fa,GCF_000711695.1_Tilletiaria_anomala_UBC_951_v1.0_genomic.fna.gz
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
405,drechmeria_coniospora_gca_001625195,EnsemblFungi,98403,ASM162519v1,GCA_001625195.1,2016-03-BiotechnologyResearchInstituteChineseAcademyofAgriculturalSciences,N,N,N,Y,...,28,"Biotechnology Research Institute, Chinese Academy of Agricultural Sciences","Annotation submitted by Biotechnology Research Institute, Chinese Academy of Agricultural Sciences",2021-04-20,8445,8236,141,26975455,Drechmeria_coniospora_gca_001625195.ASM162519v1.dna.toplevel.fa,identical_genomic.fna.gz
406,hyphopichia_burtonii_nrrl_y_1933_gca_001661395,EnsemblFungi,984485,Hypbu1,GCA_001661395.1,2016-09-DOEJointGenomeInstitute,N,N,N,Y,...,243,NCBI RefSeq,Annotation submitted by NCBI RefSeq,2017-02-15,6166,5995,171,27535936,Hyphopichia_burtonii_nrrl_y_1933_gca_001661395.Hypbu1.dna.toplevel.fa,GCF_001661395.1_Hypbu1_genomic.fna.gz
407,babjeviella_inositovora_nrrl_y_12698_gca_001661335,EnsemblFungi,984486,Babin1,GCA_001661335.1,2016-09-DOEJointGenomeInstitute,N,N,N,Y,...,211,DOE Joint Genome Institute,Annotation submitted by DOE Joint Genome Institute,2020-02-03,6795,6397,393,27535936,Babjeviella_inositovora_nrrl_y_12698_gca_001661335.Babin1.dna.toplevel.fa,GCF_001661335.1_Babin1_genomic.fna.gz
408,suhomyces_tanzawaensis_nrrl_y_17324_gca_001661415,EnsemblFungi,984487,Canta1,GCA_001661415.1,2016-09-DOEJointGenomeInstitute,N,N,N,Y,...,249,DOE Joint Genome Institute,Annotation submitted by DOE Joint Genome Institute,2019-11-29,6143,5884,257,27535936,Suhomyces_tanzawaensis_nrrl_y_17324_gca_001661415.Canta1.dna.toplevel.fa,GCF_001661415.1_Canta1_genomic.fna.gz
409,vittaforma_corneae_atcc_50505_gca_000231115,EnsemblFungi,993615,Vitt_corn_V1,GCA_000231115.1,2012-12-BroadInstitute,N,N,N,Y,...,314,Broad Institute,Annotation submitted by Broad Institute,2024-01-02,2293,2239,54,na,Vittaforma_corneae_atcc_50505_gca_000231115.Vitt_corn_V1.dna.toplevel.fa,GCF_000231115.1_Vitt_corn_V1_genomic.fna.gz

In [26]:
selected_columns = [
    'division',
    'assembly',
    'bioproject',
    'organism_name',
    'infraspecific_name',
    '#assembly_accession',
    'genome_size',
    'fasta_filename',
    'downloaded_filename'
]

filtered_selected_df = filtered_df[selected_columns].copy()

# Optional: reset index
filtered_selected_df.reset_index(drop=True, inplace=True)

filtered_selected_df.to_csv("genomes.csv")

In [28]:
df = pd.read_csv("assembly_summary_fungi.txt",sep='\t')
df

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ##  See ftp://ftp.ncbi.nlm.nih.gov/genomes/README_assembly_summary.txt for a description of the columns in this file.
#assembly_accession bioproject   biosample      wgs_master        refseq_category  taxid   species_taxid organism_name                  infraspecific_name          isolate version_status assembly_level  release_type genome_rep seq_rel_date asm_name       asm_submitter                                                                    gbrs_paired_asm paired_asm_comp ftp_path                                                                                excluded_from_refseq relation_to_type_material                       asm_not_live_date assembly_type group genome_size genome_size_ungapped gc_percent replicon_count scaffold_count contig_count annotation_provider                                                              annotation_name                                                                                          annotation_date total_gene_count protein_coding_gene_count non_coding_gene_count                                                                                                             pubmed_id
GCF_041956525.1     PRJNA1175690 SAMN39447127   JAZGQV000000000.1 reference genome 4840    4840          Rhizomucor pusillus            strain=CBS 183.67           na      latest         Scaffold        Major        Full       2024-09-16   Rhipu1         DOE Joint Genome Institute                                                       GCA_041956525.1 identical       https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/041/956/525/GCF_041956525.1_Rhipu1         na                   na                                              na                haploid       fungi 25384556    24979024             45.000000  0              48             437          DOE Joint Genome Institute                                                       Annotation submitted by DOE Joint Genome Institute                                                       2024-10-23      11084            10974                     110                                                                                                                                39266695
GCF_000002945.2     PRJNA127     SAMEA3138176   na                reference genome 4896    4896          Schizosaccharomyces pombe      strain=972h-                na      latest         Chromosome      Major        Full       2019-07-23   ASM294v3       S. pombe European Sequencing Consortium (EUPOM)                                  GCA_000002945.3 different       https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/002/945/GCF_000002945.2_ASM294v3       na                   na                                              na                haploid       fungi 12571820    12571420             36.000000  3              3              3            PomBase                                                                          Annotation submitted by PomBase                                                                          2024-08-16      12645            5124                      7489                                                                                      2446871;2780299;4046021;6092057;11859360;15811919
GCF_003054445.1     PRJNA545694  SAMN08558011   na                reference genome 4909    4909          Pichia kudriavzevii            strain=CBS573               na      latest         Complete Genome Major        Full       2018-04-17   ASM305444v1    University College Dublin                                                        GCA_003054445.1 different       https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/003/054/445/GCF_003054445.1_ASM305444v1    na                   assembly from heterotypic synonym type material na                haploid       fungi 10812555    10812555             38.500000  5              5              5            University College Dublin                                                        Annotation submitted by University College Dublin                                                        2019-06-16      5324             5139                      185                                                                                                                                      na
GCF_000243375.1     PRJNA79345   SAMEA2272433   na                reference genome 4950    4950          Torulaspora delbrueckii        strain=type strain:CBS 1146 na      latest         Chromosome      Major        Full       2011-12-08   ASM24337v1     Wolfe Laboratory, Smurfit Institute of Genetics, Trinity College Dublin, Ireland GCA_000243375.1 identical       https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/243/375/GCF_000243375.1_ASM24337v1     na                   assembly designated as neotype                  na                haploid       fungi 9220678     9218568              42.000000  8              8              8            Wolfe Laboratory, Smurfit Institute of Genetics, Trinity College Dublin, Ireland Annotation submitted by Wolfe Laboratory, Smurfit Institute of Genetics, Trinity College Dublin, Ireland 2025-07-15      5174             4970                      204                                                                                                                                22123960
...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ...
GCF_041146345.1     PRJNA1175686 SAMN40983588   JBFMKM000000000.1 reference genome 2781224 2781224       Neodothiora populina           strain=CPC 39397            na      latest         Contig          Major        Full       2024-08-08   N_Populina_1.0 University of Alaska Fairbanks                                                   GCA_041146345.1 identical       https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/041/146/345/GCF_041146345.1_N_Populina_1.0 na                   na                                              na                haploid       fungi 23962758    23962758             51.000000  0              18             18           University of Alaska Fairbanks                                                   Annotation submitted by University of Alaska Fairbanks                                                   2024-10-23      7339             7339                      0                                                                                                                                        na
GCF_028827545.1     PRJNA973687  SAMN30185328   JAPWDQ000000000.1 reference genome 2819901 2819901       Penicillium diatomitis         strain=IBT 30728            na      latest         Contig          Major        Full       2023-02-23   ASM2882754v1   Aalborg University                                                               GCA_028827545.1 identical       https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/028/827/545/GCF_028827545.1_ASM2882754v1   na                   na                                              na                haploid       fungi 33965862    33965862             49.000000  0              19             19           Aalborg University                                                               Annotation submitted by Aalborg University                                                               2023-06-06      9582             9580                      0                                                                                                                                  36726175
GCF_038363925.1     PRJNA1140273 SAMN32724326   JAQQWL000000000.1 reference genome 2905665 2905665       Apiospora phragmitis           strain=CBS 135458           na      latest         Contig          Major        Full       2024-04-17   ASM3836392v1   Aalborg university                                                               GCA_038363925.1 identical       https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/038/363/925/GCF_038363925.1_ASM3836392v1   na                   assembly from type material                     na                haploid       fungi 52445507    52445507             49.500000  0              18             18           Aalborg university                                                               Annotation submitted by Aalborg university                                                               2024-07-31      15411            15411                     0                                                                                                                                        na
GCF_021821965.1     PRJNA1031633 SAMN14823605   JACCJH000000000.1 reference genome 3039483 3039483       Ordospora pajunii              strain=FI-F-10              na      latest         Contig          Major        Full       2022-02-01   FI-F-10 v. 1   Illinois Institute of Technology                                                 GCA_021821965.1 identical       https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/021/821/965/GCF_021821965.1_FI-F-10_v._1   na                   assembly from type material                     na                haploid       fungi 2206487     2206487              43.000000  0              22             22           Illinois Institute of Technology                                                 Annotation submitted by Illinois Institute of Technology                                                 2023-10-30      1877             1826                      51                                                                                                                                       na
GCF_964197705.1     PRJNA1256999 SAMEA115480917 CAXMXA000000000.1 reference genome 3158075 3158075       Penicillium psychrofluorescens na                          KMR99   latest         Chromosome      Major        Full       2025-01-17   Pfluo_KMR99    THE UNIVERSITY OF NEW SOUTH WALES                                                GCA_964197705.1 different       https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/964/197/705/GCF_964197705.1_Pfluo_KMR99    na                   na                                              na                haploid       fungi 26257727    26257727             52.000000  6              8              8            THE UNIVERSITY OF NEW SOUTH WALES                                                Annotation submitted by THE UNIVERSITY OF NEW SOUTH WALES                                                2025-05-05      9618             9519                      99                                                                                                                                       na

[660 rows x 1 columns]